### ISSUE TITLE
memLayout sometimes empty

### ISSUE THREAD

**Issue by BillDietrich** [sebhildebrandt/systeminformation#307] opened 2019-11-27 17:52 UTC
On Linux Mint 19.2 at least, and using systeminformation 4.15.3 or 4.16.0 at least:

If I do si.getAllData("", ""), among the rest of the results I will get memLayout that is an array containing one element, with valid contents.  There is one bank of RAM in the system, this is correct.

If I do si.getStaticData() or si.memLayout(), I will get memLayout that is an empty array.

**Comment by sebhildebrandt** [comment] 2019-11-27 17:56
@BillDietrich just testet it on one of my linux machines (not mint), latest source .... no issues there - can't reproduce this behavior at the moment ... need to make a little more investigation

**Comment by sebhildebrandt** [comment] 2019-11-27 17:59
@BillDietrich What is the output of 

```
dmidecode -t memory
```

and ... did you run all three scripts with the same user permissions?

**Comment by BillDietrich** [comment] 2019-11-27 18:07
All three times run as normal user, not root.

$ sudo dmidecode -t memory
[sudo] password for user1:     
# dmidecode 3.1
Getting SMBIOS data from sysfs.
SMBIOS 2.6 present.

Handle 0x001D, DMI type 16, 15 bytes
Physical Memory Array
	Location: System Board Or Motherboard
	Use: System Memory
	Error Correction Type: None
	Maximum Capacity: 8 GB
	Error Information Handle: Not Provided
	Number Of Devices: 2

Handle 0x001F, DMI type 17, 28 bytes
Memory Device
	Array Handle: 0x001D
	Error Information Handle: Not Provided
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 4096 MB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_A
	Bank Locator: DIMM_A
	Type: DDR3
	Type Detail: Synchronous
	Speed: 1066 MT/s
	Manufacturer: CE80
	Serial Number: 49080000  
	Asset Tag: 1443           
	Part Number: CT51264BF160B.C16F
	Rank: 2

Handle 0x0021, DMI type 17, 28 bytes
Memory Device
	Array Handle: 0x001D
	Error Information Handle: Not Provided
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 4096 MB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_B
	Bank Locator: DIMM_B
	Type: DDR3
	Type Detail: Synchronous
	Speed: 1066 MT/s
	Manufacturer: 9801
	Serial Number: 01042701  
	Asset Tag: 1818           
	Part Number: KTA-MB1066K2/4G   
	Rank: 2

**Comment by BillDietrich** [comment] 2019-11-27 18:12
Now I'm confused; looks like I was getting empty array on Linux all the time, including when using si.getAllData("", "").  Maybe it was only on Windows 10 that I was seeing memLayout non-empty.

**Comment by sebhildebrandt** [comment] 2019-11-27 18:14
@BillDietrich yes ... I was also wondering ... this machine has TWO memory bricks (not one as you described in your initial statement). Closing it for now as it needs admin privileges to perform `dmidecode`, OK?

**Comment by sebhildebrandt** [comment] 2019-11-27 18:15
@BillDietrich btw: THANK you for your testing, inputs, suggestions, ... very appreciated!

**Closed by sebhildebrandt** 2019-11-27 18:14 UTC

**Comment by BillDietrich** [comment] 2019-11-27 18:17
Yes, it works if I run my app with admin privileges.  Sorry for the false alarm.

Is it documented that some things don't work, or behave differently, with/without admin privileges ?

**Comment by sebhildebrandt** [comment] 2019-11-27 18:46
@BillDietrich One more thing: can you run the following command on your linux/mint machine:

```
sudo dmidecode -t 0,13,16
```

Thank you in advance for providing the output.

**Comment by BillDietrich** [comment] 2019-11-27 18:54
$ sudo dmidecode -t 0,13,16
[sudo] password for user1:     
# dmidecode 3.1
Getting SMBIOS data from sysfs.
SMBIOS 2.6 present.

Handle 0x001C, DMI type 13, 22 bytes
BIOS Language Information
	Language Description Format: Long
	Installable Languages: 1
		en|US|iso8859-1
	Currently Installed Language: en|US|iso8859-1

Handle 0x001D, DMI type 16, 15 bytes
Physical Memory Array
	Location: System Board Or Motherboard
	Use: System Memory
	Error Correction Type: None
	Maximum Capacity: 8 GB
	Error Information Handle: Not Provided
	Number Of Devices: 2

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
	Vendor: Dell Inc.
	Version: A11
	Release Date: 01/06/2011
	Address: 0xF0000
	Runtime Size: 64 kB
	ROM Size: 2048 kB
	Characteristics:
		MCA is supported
		PCI is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		ESCD support is available
		Boot from CD is supported
		Selectable boot is supported
		BIOS ROM is socketed
		EDD is supported
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		Print screen service is supported (int 5h)
		8042 keyboard services are supported (int 9h)
		Serial services are supported (int 14h)
		Printer services are supported (int 17h)
		CGA/mono video services are supported (int 10h)
		ACPI is supported
		USB legacy is supported
		ATAPI Zip drive boot is supported
		BIOS boot specification is supported
		Targeted content distribution is supported
	BIOS Revision: 1.1
	Firmware Revision: 1.1

**Comment by BillDietrich** [comment] 2019-11-27 18:56
More about the admin-privilege thing: I see that SMART status of disks on my Linux system is "unknown" if I'm running non-admin, SMART status of hard disk is "Ok" if I'm running as admin.
