### ISSUE TITLE
si.fsSize get empty on some windows

### ISSUE THREAD

**Issue by weiweian90** [sebhildebrandt/systeminformation#395] opened 2020-08-10 09:29 UTC
systeminformation.fsSize get empty on some windows, and I try to get logicaldisk by wmic commond in terminal,
there commond is :    "wmic logicaldisk get Caption,FileSystem,FreeSpace,Size",  as same of the source code, but get "Caption  FileSystem  FreeSpace  Size  \r\r\nC:       NTFS                         \r\r\nD:       NTFS                         \r\r\n\r\r\n" . no FreeSpace and Size, sometimes even no Caption and FileSystem, like "\r\r\n\r\r\n".

it just happens on some windows,

**Comment by weiweian90** [comment] 2020-08-11 12:18
anyone has the same problem ???

**Comment by sebhildebrandt** [comment] 2020-08-11 15:49
@weiweian90 need to check it and make some investigation why this can happen .. will reply again, as soon as I found out something ...

**Comment by weiweian90** [comment] 2020-08-12 06:19
> @weiweian90 need to check it and make some investigation why this can happen .. will reply again, as soon as I found out something ...

appreciate for you reply, I will be continue attention

**Comment by sebhildebrandt** [comment] 2020-11-08 07:53
@weiweian90 Did you made any further observations concerning this behaviour? I cannot reproduce it on any of my machines here.

**Comment by sebhildebrandt** [comment] 2020-12-06 15:02
@weiweian90 Well, **this** is probably the solution for getting again the missing output:

- Disable and stop wmi service (also stops IP Helper)
- cmd > wmimgmt /resetrepository
- Enable and start wmi service, start IP Helper service

Or in Powershell you can try:

```
PS> start-service -Name winmgmt
```

Closing it for now.

**Closed by sebhildebrandt** 2020-12-06 15:02 UTC
Labels: Investigation

**Comment by weiweian90** [comment] 2020-12-07 02:12
> @weiweian90 Well, **this** is probably the solution for getting again the missing output:
> 
> * Disable and stop wmi service (also stops IP Helper)
> * cmd > wmimgmt /resetrepository
> * Enable and start wmi service, start IP Helper service
> 
> Or in Powershell you can try:
> 
> ```
> PS> start-service -Name winmgmt
> ```
> 
> Closing it for now.

thanks, I will try when face again
