### ISSUE TITLE
Question - opendirectoryd

### ISSUE THREAD

**Issue by mschwartz** [sebhildebrandt/systeminformation#119] opened 2018-03-20 21:14 UTC
I am calling various methods you provide in a loop 1/sec.

Some of them cause opendirectoryd process on my Mac to use 100% CPU (100% of one core).

Any ideas about this?

si.networkStats() is one of the major offenders.  If I comment out calling it, opendirectoryd CPU usage drops by roughly half.

**Comment by sebhildebrandt** [comment] 2018-03-20 21:40
Hi @mschwartz 
I will try to identify where the problem might be this weekend.

**Comment by sebhildebrandt** [comment] 2018-03-25 09:21
Hi @mschwartz 
I tried to identify the problem, but I cannot reproduce it here ... using `si.networkStats()` in a 1 sec loop and no process uses more than 1% CPU, overall the whole system is at 3% - tried it on two Macs here (both MacOS 10.13)

I think the problem could be your network configuration (?). The underlying command to get the network stats is `netstat -bI en0` (for interface en0). So maybe this causes some trouble in your case. Can you try to run this command in the command line in a loop and see the performance impact?

**Comment by mschwartz** [comment] 2018-03-25 16:56
Yeah, I looked at your sources and ran the commands by hand as you suggest.  I only see opendirectoryd consume high CPU when running in nodejs.

It is odd.

I was calling several of the si.* methods and commented them out one by one.  Not any one of them used 100%.  Combined, they did.

**Comment by sebhildebrandt** [comment] 2018-03-26 12:42
@mschwartz : Closing it for now ... if you have some more information or details, how to reproduce it, please reopen this issue again, OK?

**Closed by sebhildebrandt** 2018-03-26 12:42 UTC
Labels: Investigation
