### ISSUE TITLE
si.diskLayout does not match with si.fsSize

### ISSUE THREAD

**Issue by Izdatyi** [sebhildebrandt/systeminformation#176] opened 2018-11-13 23:01 UTC
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

diskLayout[0] <=> fsSize[0]
diskLayout[1] <=> fsSize[1]
I think same disks must have same indexes

### Actual behavior

diskLayout[0] <=> fsSize[1]
diskLayout[1] <=> fsSize[0]

### Steps to reproduce the problem

si.getAllData()

### Specifications 

- package version: see screenshot
- operating system: Windows 10 x64
- hardware: Desktop

![inkedsnip_20181114003629_li](https://user-images.githubusercontent.com/7038127/48448704-8a8fc500-e7a8-11e8-9087-d89964fbd0a1.jpg)

**Comment by sebhildebrandt** [comment] 2018-11-16 15:37
@Izdatyi - well I understand the problem you are describing ... the only thing is that 

- there is not always a :1 relationship between `DiskLayout` and `Filesystem`. You can have multiple file systems per disk ..
- and in case that there IS a 1:1 relationship, I need to find out, how windows tells me which file system is on what disk.

For the second one, I will probably find a solution ...

**Comment by Izdatyi** [comment] 2018-11-16 16:33
My problem is how to associate items from `DiskLayout` and `Filesystem`
You can simply add a unique key (like `uid`) to both `DiskLayout` and `Filesystem`
In this case user can associate and get info for item from `DiskLayout` by searching this key in `Filesystem`

**Comment by sebhildebrandt** [comment] 2018-11-16 16:39
The problem is, that the underlying function for `fsDisk` (`wmic logical disk`) does not give any hint how this is related to any physical disk... so therefore I have no reliable information was they are connected.

**Comment by sebhildebrandt** [comment] 2019-03-01 20:26
As I cannot find any reliable method to match this, the only possibility would be to sort it by size ... but that also is not reliable ... so I am closing it for now, but keep it on my list.

**Closed by sebhildebrandt** 2019-03-01 20:26 UTC
Labels: enhancement

**Comment by nrpatten** [comment] 2019-05-21 09:33
Hello @sebhildebrandt,

I am having the same issue with the relationship between `DiskLayout` and `fsSize` not sure if this will work but could you not add the drive letter to `DiskLayout` that way it is sortable.

eg Unsorted 
![unsorted](https://user-images.githubusercontent.com/4833541/58084573-7b2d8080-7bfe-11e9-9b4e-ef959bda4b46.jpg)

Sorted using `interfaceType`
![sorted](https://user-images.githubusercontent.com/4833541/58084630-9a2c1280-7bfe-11e9-999b-90bf9a48b51b.jpg)

Using `interfaceType` is not going to work in my app but it does show if a drive letter was added it would make it easy, Im just not sure if the returns will align correctly with a drive letter..

Thanks for your time.
