### ISSUE TITLE
currentload on windows systems doesn´t show total usage

### ISSUE THREAD

**Issue by BolverBlitz** [sebhildebrandt/systeminformation#333] opened 2020-01-27 16:16 UTC
**Describe the bug**
I´m wondering how to read the total CPU usage. It should be si.cpu().currentload but that almost always result 1,8% on my systen (used 23%)

**To Reproduce**
const si = require('systeminformation');
i.currentLoad().then(load => {
	var sum = 0;
	for(i in load.cpus){
		sum = sum + load.currentload;
	}
	console.log("Summe aus CPUs: " + sum/load.cpus.length)
	console.log("Currentload: " + load.currentload)
});

**Current Output**
Summe aus CPUs: 1.8349623825136023
Currentload: 1.8349623825136026

**Expected behavior**
Get CPU load like shown in Taskmanager
![grafik](https://user-images.githubusercontent.com/35345288/73190558-783c4580-4126-11ea-8d4a-e20ee45570d9.png)

*Edit:
I run that multiple times in PS:
Get-WmiObject -class win32_processor | Measure-Object -property LoadPercentage -Average | Select-Object -ExpandProperty Average
Returns: 4,5-61 but also avrages arround the taskmanager shownen value

**Environment (please complete the following information):**
 - systeminformation package version: systeminformation@4.19.2
 - OS: Windows Server 2019 Datacenter
 - Hardware: Cisco C220 M3 (2x E5-2667v2)

**Comment by sebhildebrandt** [comment] 2020-01-27 18:01
@BolverBlitz ... need to check this. I basically use node internal functions... can you provide the output of the following (in node):

```
os.cpus();
os.loadavg();
```

Thank you in advance.

**Comment by BolverBlitz** [comment] 2020-01-27 21:14
[
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 14968750,
      nice: 0,
      sys: 10068437,
      idle: 763819250,
      irq: 236296
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 8585203,
      nice: 0,
      sys: 3858390,
      idle: 776412140,
      irq: 169781
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 23469234,
      nice: 0,
      sys: 9472062,
      idle: 755914437,
      irq: 172109
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 6386531,
      nice: 0,
      sys: 3296796,
      idle: 779172406,
      irq: 134125
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 23749750,
      nice: 0,
      sys: 7828046,
      idle: 757277937,
      irq: 199234
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 24383468,
      nice: 0,
      sys: 3362000,
      idle: 761110265,
      irq: 138250
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 17093656,
      nice: 0,
      sys: 7010656,
      idle: 764751421,
      irq: 162625
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 10009734,
      nice: 0,
      sys: 4369609,
      idle: 774476390,
      irq: 137828
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 16657031,
      nice: 0,
      sys: 8994093,
      idle: 763204609,
      irq: 151843
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 7101750,
      nice: 0,
      sys: 4751250,
      idle: 777002734,
      irq: 79718
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 15027609,
      nice: 0,
      sys: 7864718,
      idle: 765963406,
      irq: 137843
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 20018437,
      nice: 0,
      sys: 3555093,
      idle: 765282203,
      irq: 139828
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 13962296,
      nice: 0,
      sys: 6268062,
      idle: 768625375,
      irq: 143390
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 7637484,
      nice: 0,
      sys: 3975078,
      idle: 777243156,
      irq: 133750
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 13099328,
      nice: 0,
      sys: 6364265,
      idle: 769392125,
      irq: 131593
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 18309062,
      nice: 0,
      sys: 6260062,
      idle: 764286593,
      irq: 150140
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 9773968,
      nice: 0,
      sys: 8462609,
      idle: 770619140,
      irq: 148671
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 5552062,
      nice: 0,
      sys: 4846312,
      idle: 778457343,
      irq: 90187
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 10554312,
      nice: 0,
      sys: 7911796,
      idle: 770389609,
      irq: 139078
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 5133750,
      nice: 0,
      sys: 4888546,
      idle: 778833421,
      irq: 94625
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 9060234,
      nice: 0,
      sys: 7376203,
      idle: 772419281,
      irq: 140500
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 4868562,
      nice: 0,
      sys: 5917906,
      idle: 778069250,
      irq: 93578
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 10773156,
      nice: 0,
      sys: 7363531,
      idle: 770719015,
      irq: 144437
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 4995765,
      nice: 0,
      sys: 4916812,
      idle: 778943125,
      irq: 99281
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 8021859,
      nice: 0,
      sys: 7166765,
      idle: 773667078,
      irq: 156828
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 6008453,
      nice: 0,
      sys: 4516109,
      idle: 778331140,
      irq: 94937
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 10423562,
      nice: 0,
      sys: 7216156,
      idle: 771215984,
      irq: 159046
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 4689171,
      nice: 0,
      sys: 4524281,
      idle: 779642250,
      irq: 102500
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 9166109,
      nice: 0,
      sys: 7393359,
      idle: 772296234,
      irq: 232968
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 6903359,
      nice: 0,
      sys: 18346734,
      idle: 763605593,
      irq: 107796
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 9203578,
      nice: 0,
      sys: 8542921,
      idle: 771109187,
      irq: 176140
    }
  },
  {
    model: 'Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz',
    speed: 3300,
    times: {
      user: 6272968,
      nice: 0,
      sys: 7045078,
      idle: 775537640,
      irq: 110312
    }
  }
]

Load avg: 0,0,0

**Comment by sebhildebrandt** [comment] 2020-01-27 22:33
@BolverBlitz thank you! I looked at your code. Maybe your calculation is not really correct. Could you try the following code snippet:

```
const si = require('systeminformation');

setInterval(function() {
        si.currentLoad().then(data => {
            let sum = 0;
            for (let i of data.cpus){
                sum += i.load;
            }
            console.log(sum / data.cpus.length);
        })
}, 1000)
```

This should continuously print out the current load (full sum of all cpus).

**Comment by BolverBlitz** [comment] 2020-01-27 23:50
Well i can´t realy figure out why that happens.
The code given top isn´t the actual code i´m using, I have si as promise being resolved. Anyway that seems to work just fine exept for one thing.

Running my version returns 2.4% -  Thats wrong
Now running your code:
```js
const si = require('systeminformation');

setInterval(function() {
        si.currentLoad().then(data => {
            let sum = 0;
            for (let i of data.cpus){
                sum += i.load;
            }
            console.log("Summe: " + sum / data.cpus.length);
            console.log("Currentload: " + data.currentload)
        })
}, 1000)
```

That returns also 2.4% BUT only the first time, after that it works fine and shows 24%
Does that happen on your Hardware aswell?

Run1: The Server i found the problem (Stressed with server stuff)
Summe: 2.428999520691262
Currentload: 2.4290239149646533
Summe: 21.07425628415435
Currentload: 21.0928391728539
Summe: 24.117074391440145
Currentload: 24.151771715271245
Summe: 23.5414090568029
Currentload: 23.56032406393694

Run2: Windows 10 Pro (Stressed with Cinebench 2 Threds)
Summe: 8.037667731309911
Currentload: 8.03522328826418
Summe: 40.55013484036473
Currentload: 40.50864361702128
Summe: 41.838808872033034
Currentload: 41.73711254765456
Summe: 41.50573803677587
Currentload: 41.43307347818875

Run3: Raspberry PI 4 Raspian (Stressed with stress -c 2)
Summe: 11.302275807765316
Currentload: 10.639397696213383
Summe: 56.94607843137255
Currentload: 57.14285714285714
Summe: 55.38870187250158
Currentload: 55.949367088607595

So that seems to be a constant thing... Is that a problem from systeminformation/nodeJS or my implementation of systeminformation?

Here is my full code:
https://github.com/BolverBlitz/VGN-Infobot/blob/master/src/Hardware.js
and the file calling it
https://github.com/BolverBlitz/VGN-Infobot/blob/master/Test.js

**Comment by sebhildebrandt** [comment] 2020-01-28 05:23
@BolverBlitz thank you for your tests. Will have a look on it later today.

**Comment by sebhildebrandt** [comment] 2020-01-29 10:00
@BolverBlitz So, I testet it once again (Raspberry PI, Linux bare metal, Mac) and it works fine ... values correspond also to output of the `top` command.

What you need to know: when you call this function the first time, this can only give the CPU usage since startup (which is normally not what you want). 

As you see it in your test for your server: 2.4% but then as soon as you call it the second time, you get the load BETWEEN the two calls (24%) which is, what we also see in the data below of your graph. So this should be accurate. 

For your Raspberry: also here this is fine, starting with the second call, you have >50% load (which is caused by `serve -c 2`... this seems to be absolutely correct to me.

I also had a look at you code VGN-Infobot, ... so here you would get the load between the last and the current call of `OS.Hardware`. 

Maybe I do not get the point what you are missing?

**Comment by BolverBlitz** [comment] 2020-01-30 16:30
Okay, i overlooked the botom part of the padge with the second call, then i´ll have a look at my code and how to fix it. 

Thanks for the help

**Comment by sebhildebrandt** [comment] 2020-01-30 18:34
closing It for now.

**Closed by sebhildebrandt** 2020-01-30 18:34 UTC
Labels: Investigation
