### ISSUE TITLE
Not able to get system information.

### ISSUE THREAD

**Issue by anilabsinc-harpreet** [sebhildebrandt/systeminformation#354] opened 2020-03-24 14:23 UTC
I used follwing function to get system information:
async function systemData() {
      try {
        const data = await si.system();
        console.log('system Information:', data);
      } catch (e) {
        console.log(e);
      }
    }
Promise status is 'Pending'.

**Comment by sebhildebrandt** [comment] 2020-03-24 17:14
@anilabsinc-harpreet can you provide some more information about OS, OS-Version, node Version, systeminformation version, hardware ...  Thank you in advance

**Comment by sebhildebrandt** [comment] 2020-03-24 17:19
@anilabsinc-harpreet testet the following code on different machines ... no issues. cannot reproduce your findings ...

```
const si = require('systeminformation');

async function systemData() {
	try {
		const data = await si.system();
		console.log('system Information:', data);
	} catch (e) {
		console.log(e);
	}
}

systemData();
```

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 04:13
@sebhildebrandt I am using Linux operating system. Please check follwoing details:
os: 'Linux',
os-platform: 'x64',
node-version: '8.16.0',

Hardware details are:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 142
Model name:            Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Stepping:              9
CPU MHz:               499.813
CPU max MHz:           3100.0000
CPU min MHz:           400.0000
BogoMIPS:              5424.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0-3

**Comment by sebhildebrandt** [comment] 2020-03-25 06:22
@anilabsinc-harpreet I still cannot see which linux distribution you are using ... can you give some more details ... please also run 

```
cat /etc/*-release; cat /usr/lib/os-release; cat /etc/openwrt_release
```

I also see your node version is pretty outdated ... (this should not be the reason for your issue)

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 06:34
I execute the above mention command and it returns:

openwrt_release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
cat: /etc/openwrt_release: No such file or directory

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 07:14
@sebhildebrandt I really need system information. Could you help me on this?

**Comment by sebhildebrandt** [comment] 2020-03-25 07:50
@anilabsinc-harpreet ... very clear. Will make further investigation. I will try to test this on one of my older machines with Ubuntu 16.4 ... then I will again review my code ... will come back in the afternoon to share my findings.

**Comment by sebhildebrandt** [comment] 2020-03-25 07:56
@anilabsinc-harpreet ... testet it on ubuntu 16.4 (with node 6 insalled). As node 6 does not have `async` functions I did this: 

```
const si = require('systeminformation');

si.system().then(result => {
	console.log(result)
})
```

... and it work with no issues ... can you in the meantime also try this exact code snippet?

**Comment by sebhildebrandt** [comment] 2020-03-25 08:00
@anilabsinc-harpreet and maybe you also can try (command line):

```
dmidecode -t system 2>/dev/null

cat /sys/devices/virtual/dmi/id/product_name
cat /sys/devices/virtual/dmi/id/product_serial
cat /sys/devices/virtual/dmi/id/product_uuid
cat /sys/devices/virtual/dmi/id/product_version
cat /sys/devices/virtual/dmi/id/sys_vendor
```

Please post all results here...

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 08:33
@sebhildebrandt  I tried above mention code but didn't get anything and also execute all the above commands one by one, please check:
1. dmidecode -t system
# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 3.0.0 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: Dell Inc.
	Product Name: Vostro 15-3568
	Version: Not Specified
	Serial Number: 9FCJ0F2
	UUID: 4C4C4544-0046-4310-804A-B9C04F304632
	Wake-up Type: Power Switch
	SKU Number: 0794
	Family: Vostro

Handle 0x0021, DMI type 12, 5 bytes
System Configuration Options
	Option 1: Default string

Handle 0x0022, DMI type 15, 35 bytes
System Event Log
	Area Length: 4 bytes
	Header Start Offset: 0x0000
	Header Length: 2 bytes
	Data Start Offset: 0x0002
	Access Method: Indexed I/O, one 16-bit index port, one 8-bit data port
	Access Address: Index 0x046A, Data 0x046C
	Status: Invalid, Not Full
	Change Token: 0x00000000
	Header Format: No Header
	Supported Log Type Descriptors: 6
	Descriptor 1: End of log
	Data Format 1: OEM-specific
	Descriptor 2: End of log
	Data Format 2: OEM-specific
	Descriptor 3: End of log
	Data Format 3: OEM-specific
	Descriptor 4: End of log
	Data Format 4: OEM-specific
	Descriptor 5: End of log
	Data Format 5: OEM-specific
	Descriptor 6: End of log
	Data Format 6: OEM-specific

Handle 0x0029, DMI type 32, 20 bytes
System Boot Information
	Status: No errors detected


2. cat /sys/devices/virtual/dmi/id/product_name
Vostro 15-3568

3. cat /sys/devices/virtual/dmi/id/product_serial
9FCJ0F2

4. cat /sys/devices/virtual/dmi/id/product_uuid
4C4C4544-0046-4310-804A-B9C04F304632

5. cat /sys/devices/virtual/dmi/id/product_version
it return empty line.

6. cat /sys/devices/virtual/dmi/id/sys_vendor
Dell Inc.

**Comment by sebhildebrandt** [comment] 2020-03-25 09:09
@anilabsinc-harpreet: Ok, the underlying commands work as expected ... 

To the test of my node code above ... what exactly happens, can try the following:

- can you start node
- then in node (interactive):
- copy/paste the above code ... 
- and then post the full output ... I actually do not have a feeling that happens on your side ... 

thank you in advance ...

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 09:28
@sebhildebrandt Actually I didn't get anything when test above node code.

**Comment by sebhildebrandt** [comment] 2020-03-25 10:23
@anilabsinc-harpreet ...cant be ... when pasting the first line you should get at least something like:

```
mycomputer# node
> const si = require('systeminformation');
undefined
```

And I would like to see al lines ...

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 11:21
@sebhildebrandt I used same and it returns:
{ manufacturer: 'Dell Inc.',
  model: 'Vostro 15-3568',
  version: '',
  serial: '-',
  uuid: '',
  sku: '-' }
but when i am using same code in my project i am not getting anything

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 11:24
@sebhildebrandt Please check this:

import si from 'systeminformation';
export const systemData = () => {
  let data = {};
  si.system().then((result) => {
    data = result;
  });
  return data;
};

and i am calling this function like this:

import * as Utilities from '../Utilities.js';
const sysData = Utilities.systemData();
console.log('sysData', sysData);

**Comment by sebhildebrandt** [comment] 2020-03-25 11:50
@anilabsinc-harpreet ... your return is at the wrong place. It should be:

```
import si from 'systeminformation';

export const systemData = () => {
	let data = {};
	si.system().then((result) => {
		data = result;
		return data;
	});
};
```

or shorter

```import si from 'systeminformation';

export const systemData = () => {
	si.system().then((result) => {
		return result;
	});
};
```

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 12:01
@sebhildebrandt it return 'undefined'

One more thing: i am getting this Error while startimg my app:
"Module not found: Can't resolve 'osx-temperature-sensor' in '/home/kav/aa_harpreet/olympus/node_modules/systeminformation/lib'
"

Is this could be generate this issue?

**Comment by sebhildebrandt** [comment] 2020-03-25 12:11
@anilabsinc-harpreet ... 

1. ok, so your code seems to be not correct. If you wrap si.system() in a function, then this also should be a promise or an async function ... which is not the case. I guess you need to refactor your own code. You can one more time verify that systeminfortmation is working correct by adding a console log INSIDE your `systemData` function just before the `return`.
2. for the second issue, here I also would need the FULL debug call stack... as this module is ONLY required for macOS I wonder, why this happens on your machine: my code explicitly checks:

```
      if (_darwin) {     //  <--------- ONLY if platform is _darwin = macOS
        let osxTemp = null;
        try {
          osxTemp = require('osx-temperature-sensor');
        } ...
      }
```

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 12:45
@sebhildebrandt  now am using :

import si from 'systeminformation';
export const systemData = async () => {
  const result = await si.system().then((data) => {
    return data;
  });
  return result;
};

and calling like this:
import * as Utilities from '../Utilities.js';
Utilities.systemData().then((result) => {
    console.log('sysData', result);
  });

this is not return anything

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 12:48
@sebhildebrandt if i am directally use this:
const si = require('systeminformation');
si.system().then(data => console.log(data));

same thing happens, not getting any console.

**Comment by sebhildebrandt** [comment] 2020-03-25 12:52
@anilabsinc-harpreet I would be happy if you provide, what I asked for ...

To the test of my node code above ... what exactly happens, can try the following:

- can you start node
- then in node (interactive):
- copy/paste the above code ...
- and then post the full output (from your node-command will the end)... I actually do not have a feeling that happens on your side ...

And you replied that there is no output which cannot be true, I need ALL lines as stated above (beginning with your node command)... One more time: I cannot reproduce your issue with the same OS version and old node version. To be able to help I need

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 12:55
@sebhildebrandt 
> const si = require('systeminformation');
undefined
> 
> si.system().then(result => {
... 	console.log(result)
... })
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> { manufacturer: 'Dell Inc.',
  model: 'Vostro 15-3568',
  version: '',
  serial: '-',
  uuid: '',
  sku: '-' }
>

**Comment by sebhildebrandt** [comment] 2020-03-25 13:47
@anilabsinc-harpreet Thank you ... will try to make some more investigation

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 13:50
@sebhildebrandt I am still facing same issue and still getting this error:

Error in ./node_modules/systeminformation/lib/cpu.js
Module not found: Can't resolve 'osx-temperature-sensor' in '/home/site/node_modules/systeminformation/lib'

This is because of above error, i am getting Promise state 'Pending'. Rest you knows well.

Thank you.

**Comment by sebhildebrandt** [comment] 2020-03-25 14:48
@anilabsinc-harpreet ... is there any call stack for your `osx-temperature-sensor` error? This looks quite strange ... as already stated above ... 

Not quite sure what is going on ... one question: do you use any transpiler or anything that changes code? The `Module not found ...` must not happen on a linux machine ...

**Comment by sebhildebrandt** [comment] 2020-03-25 14:50
@anilabsinc-harpreet last question ... already asked but did not get any answer to that: which version of systeminformation are you using? Just to be sure ...

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 15:32
@sebhildebrandt i am using systeminformation version '4.23.1'.

**Comment by anilabsinc-harpreet** [comment] 2020-03-25 15:48
@sebhildebrandt I am not using any transpiler.

**Comment by anilabsinc-harpreet** [comment] 2020-03-26 08:32
@sebhildebrandt I want to tell you something. when i execute all the above commands that you told me to run like 'cat /sys/devices/virtual/dmi/id/product_name', at that time i added 'sudo' to give permissions. I think in your code you are executing commands without 'sudo' keyword.

**Comment by anilabsinc-harpreet** [comment] 2020-03-26 13:26
Hi @sebhildebrandt  
I checked your package and put console in your package to verify. One thing is very strange that in 'system.js', you are getting platform using 'process.platform'. In my case, platform is 'undefined' and that's why it is not satisfying condition and not returing value. Now can you check that why it is happening. I am using 'systeminformation' in my Reactjs project and my react version is '16.10'.

Thanks in advance

**Comment by anilabsinc-harpreet** [comment] 2020-03-26 13:29
Hi @sebhildebrandt
I checked your package and put console in your package to verify. One thing is very strange that in 'system.js', you are getting platform using 'process.platform'. In my case, platform is 'undefined', child_process is 'undefind' and that's why it is not satisfying condition and not returing value. Now can you check that why it is happening. I am using 'systeminformation' in my Reactjs project and my react version is '16.10'.

Thanks in advance

**Comment by sebhildebrandt** [comment] 2020-03-26 14:44
@anilabsinc-harpreet  Can you point me to your project? Is there a GitHub repository? If `process.platform` is `undefined` this is strange and not related to my package instead this might be related to the way you are using the package ... is this a backend project or are you using this code in the front end (react.js)?

**Comment by anilabsinc-harpreet** [comment] 2020-03-27 04:27
@sebhildebrandt I can't point you to my project. I am using this code in front end(ReactJS).
When i typing this in node, it returns 'linux' and this is correct, but in my project it returns 'undefined'.

**Comment by sebhildebrandt** [comment] 2020-03-27 06:35
@anilabsinc-harpreet THIS explains everything ... This is a node.js package (not intended to be used in a browser). As stated in the docs: 

"It is supposed to be used as a backend/server-side library (will definilely not work within a browser)"

Please read the docs carefully. Closing this issue.

**Closed by sebhildebrandt** 2020-03-27 06:35 UTC
Labels: Investigation
