### ISSUE TITLE
TypeError: utils.sanitizeShellString is not a function

### ISSUE THREAD

**Issue by venom7aries** [sebhildebrandt/systeminformation#812] opened 2023-05-27 17:27 UTC
. node: internal/readline/emitKeypressEvents:74
throw err;
^
TypeError: utils.sanitizeShellString is not a function
at ReadStream.<anonymous» (/home/runner/systeminformation/test. js: 82:32)
at ReadStream.emit (node:events:513:28 ) at ReadStream.emit (node: domain: 489:12)
at emitKeys (node: internal/readline/utils: 357:14)
at emitKeys.next (<anonymous>)
at ReadStream.onData (node: internal/readline/emitKeypressEvents: 64:36)
at ReadStream.emit (node: events:513:28) at ReadStream.emit (node: domain: 489:12)
at addChunk (node: internal/streams/readable: 324:12)

Node. js v18.12.1

**Comment by sebhildebrandt** [comment] 2023-05-27 19:43
Hi @venom7aries ... as I a cannot reproduce your issue, can you give more context?

- OS and OS Version
- systeminformation version
- what is the context (code), you try to run your code
- if you clone the package locally and run `npm run test` and go through all of the give menu options, where does it crash

Regards

**Comment by sebhildebrandt** [comment] 2023-05-29 08:05
@venom7aries Closing it for now ... if you can provide additional information, press consider reopening this issue

**Closed by sebhildebrandt** 2023-05-29 08:05 UTC
