### ISSUE TITLE
Si.memLayout not returning anything on Linux

### ISSUE THREAD

**Issue by MeesMaas** [sebhildebrandt/systeminformation#82] opened 2017-10-10 20:43 UTC
### Expected behavior and actual behavior.
 - On windows
![photo_2017-10-10_22-37-10](https://user-images.githubusercontent.com/10887960/31409488-5e89e368-ae0c-11e7-83e5-d474e0dba934.jpg)

### Steps to reproduce the problem.
- Get linux
- Execute the following
![image](https://user-images.githubusercontent.com/10887960/31409463-460e4838-ae0c-11e7-90ec-e6da1441cf08.png)

**Comment by sebhildebrandt** [comment] 2017-10-16 07:13
Hi, can you try the following command on your linux machine:

```
dmidecode -t memory
```

maybe you need admin privileges here to get a valid output.

Thank you in advance

**Comment by MeesMaas** [comment] 2017-10-16 16:07
With Admin Privileges:
``` 
# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x0041, DMI type 16, 23 bytes
Physical Memory Array
	Location: System Board Or Motherboard
	Use: System Memory
	Error Correction Type: None
	Maximum Capacity: 32 GB
	Error Information Handle: Not Provided
	Number Of Devices: 4

Handle 0x0042, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0041
	Error Information Handle: Not Provided
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 4096 MB
	Form Factor: SODIMM
	Set: None
	Locator: ChannelA-DIMM0
	Bank Locator: BANK 0
	Type: DDR3
	Type Detail: Synchronous
	Speed: 1600 MHz
	Manufacturer: Samsung
	Serial Number: 37F11DEB
	Asset Tag: 9876543210
	Part Number: M471B5173QH0-YK0  
	Rank: 1
	Configured Clock Speed: 1600 MHz
	Minimum Voltage: 1.35 V
	Maximum Voltage: 1.5 V
	Configured Voltage: 1.35 V

Handle 0x0044, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0041
	Error Information Handle: Not Provided
	Total Width: Unknown
	Data Width: Unknown
	Size: No Module Installed
	Form Factor: DIMM
	Set: None
	Locator: ChannelA-DIMM1
	Bank Locator: BANK 1
	Type: Unknown
	Type Detail: None
	Speed: Unknown
	Manufacturer: [Empty]
	Serial Number: [Empty]
	Asset Tag: 9876543210
	Part Number: [Empty]
	Rank: Unknown
	Configured Clock Speed: Unknown
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x0045, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0041
	Error Information Handle: Not Provided
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 4096 MB
	Form Factor: SODIMM
	Set: None
	Locator: ChannelB-DIMM0
	Bank Locator: BANK 2
	Type: DDR3
	Type Detail: Synchronous
	Speed: 1600 MHz
	Manufacturer: Samsung
	Serial Number: 37F11DE4
	Asset Tag: 9876543210
	Part Number: M471B5173QH0-YK0  
	Rank: 1
	Configured Clock Speed: 1600 MHz
	Minimum Voltage: 1.35 V
	Maximum Voltage: 1.5 V
	Configured Voltage: 1.35 V

Handle 0x0047, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0041
	Error Information Handle: Not Provided
	Total Width: Unknown
	Data Width: Unknown
	Size: No Module Installed
	Form Factor: DIMM
	Set: None
	Locator: ChannelB-DIMM1
	Bank Locator: BANK 3
	Type: Unknown
	Type Detail: None
	Speed: Unknown
	Manufacturer: [Empty]
	Serial Number: [Empty]
	Asset Tag: 9876543210
	Part Number: [Empty]
	Rank: Unknown
	Configured Clock Speed: Unknown
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown
```

**Comment by sebhildebrandt** [comment] 2017-10-16 20:42
Thank you!
To be more explicit, the command returns result but does `si.memLayout()` also with admin privileges anyway returns noting (empty array)?

**Comment by sebhildebrandt** [comment] 2017-10-21 09:10
Hi again, did you manage to test `si.memLayout()` with admin privileges? Seeing the output of the underlying command, this should return correct values. Can you confirm that?

**Comment by sebhildebrandt** [comment] 2017-10-30 09:27
Closing it for now as I cannot reproduce it any more ...

**Closed by sebhildebrandt** 2017-10-30 09:27 UTC
Labels: bug
