### ISSUE TITLE
fsSize doesn't work after 5.18.0 on a Linux device

### ISSUE THREAD

**Issue by bartversluijs** [sebhildebrandt/systeminformation#815] opened 2023-06-06 19:26 UTC
**Describe the bug**
When executing the `fsSize` command, I get an empty array.  
I see that 5.18.0 introduces a new optional parameter, and the problem seems to lie there.

**To Reproduce**
1. used function 'fsSize()'
2. code snippet:
```ts
import si from 'systeminformation';

const fsSize = await si.fsSize();
console.log(fsSize); // Output = []
```

**Current Output**
As stated, the output is an empty array.

**Expected behavior**
I expect the systeminformation to return an array of all mounted file systems.

**Environment (please complete the following information):**
 - systeminformation package version: 5.18.0
 - OS: Alpine Linux 3.17.0
 - Hardware: Raspberry Pi 4

**Comment by bartversluijs** [comment] 2023-06-06 19:35
Problem sees to be the [changed command for me](https://github.com/sebhildebrandt/systeminformation/commit/8c22e42bf35c8ba057dfbfc6536139ee66046221#diff-1e1fcf4403e041a96ef6190bcffbf7ee93a87fa0a0e740ccffc6c80a6d570ff6L134-R140).

When I change the command back in the file, everything seems to work fine again.

**Comment by sebhildebrandt** [comment] 2023-06-07 03:46
@bartversluijs ... thank you for reporting! So it seems that alpine does not support this `export LC_ALL`. I reverted it back and need to see how I can deal with this ... (as I am using this is a lot of spaces) ... will need to make some test. 

I reverted it back for now. Version 5.18.1 just published.

**Comment by sebhildebrandt** [comment] 2023-06-07 05:45
@bartversluijs ... just wondering ... I tested the command on a local virtual alpine instance (alpine 3.18 virt) ... the problem here is NOT the export LC_ALL, its all about the params ... 

This one does not work here on my alpine instance:

```
df -lkPTx squashfs
```

But this one works on Alpine linux

```
df -kPT squashfs
```
  
Can you provide the output of

```
df -z
```

This is an unsupported parameter and I am interested in the output (Usage) ...

Thank you in advance!

**Comment by sebhildebrandt** [comment] 2023-06-07 06:16
@bartversluijs I see where the problem is ... by introducing the `export LC_ALL ...` no error was thrown using the extended command. So my code never got into the fallback. Concerning your issue here, I guess we are fine with the current version 5.18.1. 

I introduced this `export LC_ALL` because of another issue we had and I have to find a other solution there ;-) 

I will close this issue here again.

**Closed by sebhildebrandt** 2023-06-07 06:16 UTC

**Comment by sebhildebrandt** [comment] 2023-06-07 06:45
@bartversluijs ... I made another patch on the master branch. Would it be possible to check out the master branch and test it on your raspberry/alpine machine? If this works as expected, also the other issue has a stable fix ;-)

**Comment by bartversluijs** [comment] 2023-06-07 06:47
@sebhildebrandt thanks for investigating this!

For your information, when running `df -z`, the response is that 'z' is an unrecognized option.

But when typing, I see you responded again with another fix. So will test that out.
Have to check if I can think of something to test out the master branch, because I'm using a Docker container. But will test it out :)

**Comment by sebhildebrandt** [comment] 2023-06-07 07:18
@bartversluijs thank you! ... I will also test it inside a docker container (plus making modifications till it works) ...

**Comment by sebhildebrandt** [comment] 2023-06-07 07:18
@bartversluijs  so we will leave it for now at is it in 5.18.1 as this works, right?

**Comment by sebhildebrandt** [comment] 2023-06-07 18:28
@bartversluijs can you also test version 5.18.2 ... I just released a new version that works here in my alpine docker and also fixes my other issue.

**Comment by bartversluijs** [comment] 2023-06-08 07:29
@sebhildebrandt version 5.18.2 seems to work! Thanks!

**Comment by sebhildebrandt** [comment] 2023-06-08 13:01
@bartversluijs thank you so much for all your tests!
