### ISSUE TITLE
Linux returns null RAM info

### ISSUE THREAD

**Issue by NoobishSVK** [sebhildebrandt/systeminformation#666] opened 2022-03-19 23:50 UTC
**Describe the bug**
Whenever I ask for RAM data from Linux, the system just returns null data, or an empty string.

**To Reproduce**
1. used function 'si.memLayout()'

**Current Output**
![obrázok](https://user-images.githubusercontent.com/17816750/159142175-35f74d4c-fd92-4c21-909a-7a7df787f781.png)

**Expected behavior**
I'd expect it to work the same way as on windows: 
![obrázok](https://user-images.githubusercontent.com/17816750/159142196-fdc050bd-8e0f-4a91-a78a-14a48d6dbf3f.png)

**Environment (please complete the following information):**
 - systeminformation package version: latest
 - OS: any Linux distro - tested on EndeavourOS, Arch Linux, Artix, Fedora, Kubuntu...
 - Hardware every HW i tested this with is different, but all of them return the same result, so i believe that's irrelevant in this case

**Additional context**
The result seems to be the exact same no matter what HW and distro my testers are running.

**Comment by sebhildebrandt** [comment] 2022-03-20 06:58
@NoobishSVK need to have a look on it today. As soon as I am in the office I will try to see what the problem is. Thank you for reporting

**Comment by NoobishSVK** [comment] 2022-03-20 10:00
No worries. Thank you very much for your reply. :)

**Comment by sebhildebrandt** [comment] 2022-03-20 19:01
@NoobishSVK as I cannot reproduce this here on any machine, can you provide the output of 

```
dmidecode -t memory 2>/dev/null | grep -iE "Size:|Type|Speed|Manufacturer|Form Factor|Locator|Memory Device|Serial Number|Voltage|Part Number"
```

**Comment by NoobishSVK** [comment] 2022-03-20 21:11
User 1 - First screenshot = nonroot, second screenshot = root 
![obrázok](https://user-images.githubusercontent.com/17816750/159185911-0d178089-4f57-4140-bd56-5f4da8f6907b.png)
![obrázok](https://user-images.githubusercontent.com/17816750/159185975-e884720e-6e0d-4442-a8a5-9a66200d3521.png)

User 2 - same result without root as with the first user, so here's a root screenshot:
https://cdn.discordapp.com/attachments/688040483699818602/955211550245937152/unknown.png

Unfortunately it seems like dmidecode requires root, which is definitely not ideal for an electron app as I wouldn't want users to run it as root. I believe there's nothing you can do about that, unless there's another way of getting HW info without root. I would deem that as my fault for not knowing that.

**Comment by SagoBno** [comment] 2022-03-28 20:00
Im not sure if is the same problem, but I report this bug: https://github.com/sebhildebrandt/systeminformation/issues/670

**Comment by sebhildebrandt** [comment] 2022-11-19 10:25
@NoobishSVK closing it for now as I do not find any other possibility to get memory layout data without `dmidecode`

**Closed by sebhildebrandt** 2022-11-19 10:25 UTC
Labels: Investigation
