### ISSUE TITLE
multi PowerShell process crashed

### ISSUE THREAD

**Issue by jcindex** [sebhildebrandt/systeminformation#611] opened 2021-11-03 08:13 UTC
**Describe the bug**
After the command executed by PowerShell under Windows 10 is completed, it does not exit PowerShell in time, resulting in full CPU during cyclic sampling and system crash

**To Reproduce**
1. used function 'si.mem()' or 'si.fsSize()'
2. code snippet 'si.mem()' or 'si.fsSize()'
3. 
4. See output/error
![image](https://user-images.githubusercontent.com/7412888/140026996-c357bf1b-af59-4a3b-83f7-5ab83affda03.png)

**Current Output**
If applicable, add output to help explain your problem.

**Expected behavior**

**Environment (please complete the following information):**
 - systeminformation package version: 5.9.9
 - OS: Windows 10
 - Hardware: Personal Computer - Self assembled machine

**Additional context**

**Comment by jcindex** [comment] 2021-11-03 08:19
After testing, 'si.mem()' contains the paging file information read from the disk, and 'se.fsSize()' itself reads the disk information. This indicates that the above problems may occur as long as the disk information is read.

**Comment by sebhildebrandt** [comment] 2021-11-03 08:55
@jcindex currently I am ill but I will try to focus on that as soon as I have recovered ...

**Comment by jcindex** [comment] 2021-11-04 11:58
> @jcindex currently I am ill but I will try to focus on that as soon as I have recovered ...

Take care of your health. I will always pay attention to your reply!

**Comment by si458** [comment] 2021-11-07 10:03
@sebhildebrandt im also noticing this sorta issue when calling `users()`
before the WMI refactor it was using next to no CPU usage, now every time i call it (every 5 seconds) im seeing very HIGH cpu usage from powershell and its taking about twice a long to return the results

take care of your health first though

**Comment by sebhildebrandt** [comment] 2021-11-08 07:45
@si458 ... Thank you for your findings. Besides the general PowerShell problem... for the `users()` it seems that I have to make a decision between a faster implementation OR supporting UTF8 characters. As all my tests and researches showed, Windows will not give me a way to have both at the same time when using it inside node.js (which is a little bit frustrating). Anyway, I will first need to concentrate on solving the PowerShell issue here.

**Comment by si458** [comment] 2021-11-08 09:56
@sebhildebrandt i believe the issue with the `users()` is because of the move to powershell because i also experience the same issue here when i look at processexplorer, nodejs is running `powershell` to then run `cmd` but it seems the powershell never closes? it stays open?

**Comment by sebhildebrandt** [comment] 2021-11-08 10:01
@si458 I understand ... this is what I am investigating right now. I am currently trying to create a better `powerShell` implementation, and I hope to be able to solve this. I used the same powerShell version for quite long now in other commands without being aware of any issues (at least no one reported back to me). Will report here, as soon as I have a solution... once again thank you for reporting.

**Comment by si458** [comment] 2021-11-08 10:03
@sebhildebrandt good luck! hope you better too, any testing, ping us 👍

**Comment by sebhildebrandt** [comment] 2021-11-11 14:53
@si458 , @jcindex I now created a new issue that sums up related issues (windows/wmic/powershell). I guess this gives a better overview about the problems we currently have here. For this issue here I made some research and tests but I was not yet able to reproduce it. I created scripts where I run thousands of calls to `men()` and `fsSize()` not having one single `powerShell` instance not closing. So I need to make more research here, what the problem could be. 

I was using powerShell now for 3 years in this package, and till now I did not get any reports that we have problems here. This does not mean that there isn't a problem. It is just hard to find right now. I would be happy, if you can provide a test case where I can reproduce this issue. 

As we now are forced to use powerShell (wmic was dropped in windows 11), I am of course highly interested to solve this issue.

Thank you

**Comment by sebhildebrandt** [comment] 2021-11-21 14:54
@si458 @jcindex ... I made detailed research and it turns out that spinning up PowerShell Process is responsible for consuming   resource and time. I now created a possibility to create a persistent PowerShell which then should reduce resources by 90% ... 

It would be great if you can test the latest code here on GitHub: What you have to do to enable the persistent power shell:

- on startup (if you are running in windows): `si.powerShellStart();`
- and then again when shutting down the app: `si.powerShellRelease();`

All commands In between will then use this already pinned up powerShell. 

The implementation ist still a little hacky ... but if your results are fine and this is what you would like to use, I will make a clean up! Any comments are welcome!

**Comment by sebhildebrandt** [comment] 2022-02-14 11:40
@si458 @jcindex I testet it again here on my side and the proposed use of `si.powerShellStart()` improved the problem here drastically. I tried it with continuous loopes for both mentioned functions and `powerShell` cpu usage stays < 1% ... see the following screenshot:

<img width="538" alt="Screenshot 2022-02-14 123256" src="https://user-images.githubusercontent.com/4717960/153857727-504632fb-fdd6-4719-bd4e-3e1bde358c1d.png">

Closing it for now.

**Closed by sebhildebrandt** 2022-02-14 11:40 UTC
Labels: Investigation
