### ISSUE TITLE
networkInterfaceDefault returns the interface number

### ISSUE THREAD

**Issue by prodigitalson** [sebhildebrandt/systeminformation#253] opened 2019-06-25 02:03 UTC
**Describe the bug**
On raspbian stretch the default interface is reported as as the interface number, for example `if251`. This is within a QEMU arm64 emulation in a docker container. This is because this is what `ip route` reports for some reason. I haven't gotten a chance to try it out on my actual rpi yet so it could be a qemu and/or docker specific thing. If this were sufficient to use with `networkStats` it would be fine, but it cant be used that way.

**To Reproduce**
Assuming you already have QEMU registered you can drop this in a Dockerfile
```
FROM debian:stretch as qemubase
RUN apt-get update && apt-get install -y qemu qemu-user-static qemu-user binfmt-support

FROM raspbian/stretch:latest
COPY --from=qemubase /usr/bin/qemu-arm-static /usr/bin/
RUN apt-get update && apt-get install -y curl iproute2
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
&& apt-get install -y nodejs

RUN /usr/bin/npm install systeminformation

CMD /usr/bin/node -e "const si = require('systeminformation'); si.networkInterfaceDefault(iface => console.log('Default iface:', iface));"
```

Then:
```
docker build -rm --tag systeminformation:rpi -f path/to/Dockerfile
docker run -ti  systeminformation:rpi
```

Observer the last line of output. (Clearly there is something going on here with qemu, but im not sure thats 100% related).

**Current Output**
Something like `Default iface: if123` where 123 is the interface number in the system

**Expected behavior**
I expect output to match up with the `iface` or `ifaceName` returned by `networkInterfaces` and `networkStats` as well as nodes built in `os.networkInterfaces` (all these report as expected).

**Environment (please complete the following information):**
 - systeminformation package version:
 - OS: Host: MacOS 10.14.2, Docker Container: raspbian:stretch 
 - Hardware: MacBook Pro (Retina, 15-inch, Mid 2015)

**Additional context**
Could definitely be something unique to QEMU. This isn't an issue with systeminformation so much as it is with `ip route`, however it could be necessary to do a workaround for this.

**Comment by sebhildebrandt** [comment] 2019-06-25 05:31
@prodigitalson Thank you for reporting this. I will have a look on this later this week!

**Comment by prodigitalson** [comment] 2019-06-26 00:59
So, I got a chance to take a look at the Pi this evening. This definitely seems specific to QEMU. Perhaps something I missed or something not configured in the build images I'm using. `ip route` seems fine when run directly on the Pi. Unfortunately this throws a small wrench in plans to run unit and integration tests on my dev machine before deploying.

**Comment by sebhildebrandt** [comment] 2019-07-03 12:27
@prodigitalson so I now tested also on PI ... seems to be fine. I still leave this issue open because I would also like to make a test as described ... not sure, when I will have time for that.

**Comment by prodigitalson** [comment] 2019-07-03 13:35
Sounds good. I think its totally weirdness with QEMU in combination with Docker and a macOS dev environment.

**Comment by sebhildebrandt** [comment] 2021-02-12 15:50
@prodigitalson ... if OK I am closing this now as I cannot really reproduce this ... if you think this is still an issue, pleas feel free to reopen this ...

**Closed by sebhildebrandt** 2021-02-12 15:50 UTC
Labels: Investigation
