### ISSUE TITLE
networkStats() do not work on win10

### ISSUE THREAD

**Issue by NWIron** [sebhildebrandt/systeminformation#277] opened 2019-09-17 07:35 UTC
**Describe the bug**
When I use networkStats() to extract information of nework status, the function didn't return expected value. Probably because of the system language is Chinese?

**To Reproduce**
1. used function 'si.networkStats()'
2. all values are 0

**Environment (please complete the following information):**
 - systeminformation package version: 4.14.8
 - OS: windows 10
 - Hardware: Desktop

**Additional context**
Actually, I solved the problem by adjust the logic in netwrok.js
Line 732

/* Could be a bug
                  if ((det.iface.toLowerCase() === iface.toLowerCase() ||
                    det.mac.toLowerCase() === iface.toLowerCase() ||
                    det.ip4.toLowerCase() === iface.toLowerCase() ||
                    det.ip6.toLowerCase() === iface.toLowerCase() ||
                    (det.ifaceName.replace(/[()\[\] ]+/g, '').toLowerCase() === iface.replace(/[()\[\] ]+/g, '').toLowerCase()) &&
                    det.ifaceName.replace(/[()\[\] ]+/g, '').toLowerCase() === detail.name)) {
                    ifaceName = det.iface;
                    rx_bytes = detail.rx_bytes;
                    rx_dropped = detail.rx_dropped;
                    rx_errors = detail.rx_errors;
                    tx_bytes = detail.tx_bytes;
                    tx_dropped = detail.tx_dropped;
                    tx_errors = detail.tx_errors;
                    operstate = det.operstate;
                  }
                  */

                  if ((det.iface.toLowerCase() === iface.toLowerCase() ||
                    det.mac.toLowerCase() === iface.toLowerCase() ||
                    det.ip4.toLowerCase() === iface.toLowerCase() ||
                    det.ip6.toLowerCase() === iface.toLowerCase() ||
                    det.ifaceName.replace(/[()\[\] ]+/g, '').toLowerCase() === iface.replace(/[()\[\] ]+/g, '').toLowerCase() ||
                    det.ifaceName.replace(/[()\[\] ]+/g, '').replace('#', '_').toLowerCase() === iface.replace(/[()\[\] ]+/g, '').replace('#', '_').toLowerCase()) &&
                    (det.ifaceName.replace(/[()\[\] ]+/g, '').toLowerCase() === detail.name ||
                      det.ifaceName.replace(/[()\[\] ]+/g, '').replace('#', '_').toLowerCase() === detail.name)) {
                    ifaceName = det.iface;
                    rx_bytes = detail.rx_bytes;
                    rx_dropped = detail.rx_dropped;
                    rx_errors = detail.rx_errors;
                    tx_bytes = detail.tx_bytes;
                    tx_dropped = detail.tx_dropped;
                    tx_errors = detail.tx_errors;
                    operstate = det.operstate;
                  }

I'm not sure if this is a bug, but it works in my case.

**Comment by budoka** [comment] 2019-09-20 04:47
works too

**Comment by sebhildebrandt** [comment] 2019-10-18 10:25
@nathanwcy so what I see, besides that I found a bug is, that you also replaced "#" characters to "_" in your comparison. Could you provide the output of 

command line:
```
wmic path Win32_PerfRawData_Tcpip_NetworkInterface Get name,BytesReceivedPersec,BytesSentPersec,BytesTotalPersec,PacketsOutboundDiscarded,PacketsOutboundErrors,PacketsReceivedDiscarded,PacketsReceivedErrors /value
```

and 

```
wmic nic get MACAddress,name,NetEnabled,Speed,NetConnectionStatus,AdapterTypeId /value
```

as well as (from node.js)

```
> os.networkInterfaces()
```

Thank you in advance!

**Comment by iamluodong** [comment] 2019-10-31 10:51
from 4.9.1 ,the networkstats on windows can't work. my system is windows 10 Pro.
![image](https://user-images.githubusercontent.com/4755525/67940831-658d9f80-fc0f-11e9-8f89-63e41784eebd.png)


1. 
BytesReceivedPersec=10878059317
BytesSentPersec=7390186057
BytesTotalPersec=18268245374
Name=Intel[R] Ethernet Connection [7] I219-V
PacketsOutboundDiscarded=0
PacketsOutboundErrors=0
PacketsReceivedDiscarded=373
PacketsReceivedErrors=0


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=Npcap Loopback Adapter
PacketsOutboundDiscarded=0
PacketsOutboundErrors=0
PacketsReceivedDiscarded=0
PacketsReceivedErrors=0


2. 
AdapterTypeId=
MACAddress=
Name=Microsoft Kernel Debug Network Adapter
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=0
MACAddress=70:85:C2:AD:7F:A4
Name=Intel(R) Ethernet Connection (7) I219-V
NetConnectionStatus=2
NetEnabled=TRUE
Speed=1000000000


AdapterTypeId=
MACAddress=
Name=WAN Miniport (SSTP)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=WAN Miniport (IKEv2)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=WAN Miniport (L2TP)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=WAN Miniport (PPTP)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=WAN Miniport (PPPOE)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=0
MACAddress=9C:28:20:52:41:53
Name=WAN Miniport (IP)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=0
MACAddress=9C:28:20:52:41:53
Name=WAN Miniport (IPv6)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=0
MACAddress=9E:8E:20:52:41:53
Name=WAN Miniport (Network Monitor)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=0
MACAddress=0A:00:27:00:00:05
Name=VirtualBox Host-Only Ethernet Adapter
NetConnectionStatus=2
NetEnabled=TRUE
Speed=1000000000


AdapterTypeId=0
MACAddress=02:00:4C:4F:4F:50
Name=Npcap Loopback Adapter
NetConnectionStatus=2
NetEnabled=TRUE
Speed=1215752192

3. 
{ '以太网':
   [ { address: 'fe80::d9ba:937c:b218:536f',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '70:85:c2:ad:7f:a4',
       scopeid: 10,
       internal: false,
       cidr: 'fe80::d9ba:937c:b218:536f/64' },
     { address: '192.168.1.18',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: '70:85:c2:ad:7f:a4',
       internal: false,
       cidr: '192.168.1.18/24' } ],
  'VirtualBox Host-Only Network':
   [ { address: 'fe80::c8e1:4051:4f32:eec',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '0a:00:27:00:00:05',
       scopeid: 5,
       internal: false,
       cidr: 'fe80::c8e1:4051:4f32:eec/64' },
     { address: '192.168.56.1',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: '0a:00:27:00:00:05',
       internal: false,
       cidr: '192.168.56.1/24' } ],
  'Npcap Loopback Adapter':
   [ { address: 'fe80::6524:e13a:bd53:71cb',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '02:00:4c:4f:4f:50',
       scopeid: 12,
       internal: false,
       cidr: 'fe80::6524:e13a:bd53:71cb/64' },
     { address: '169.254.113.203',
       netmask: '255.255.0.0',
       family: 'IPv4',
       mac: '02:00:4c:4f:4f:50',
       internal: false,
       cidr: '169.254.113.203/16' } ],
  'Loopback Pseudo-Interface 1':
   [ { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true,
       cidr: '::1/128' },
     { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true,
       cidr: '127.0.0.1/8' } ] }
>

**Comment by nathanwcy** [comment] 2019-11-06 02:18
@sebhildebrandt I replaced "#" characters to "_" because I found **name** in **perfData** not matched with **ifaceName** in **interfaces** (Line 730 in network.js). I think the issue is caused by language or version of Windows 10&7 and only happened on specific computers. networkStats() works quite good under English Language environment.
Later I will attach the result of 

`wmic path Win32_PerfRawData_Tcpip_NetworkInterface Get name,BytesReceivedPersec,BytesSentPersec,BytesTotalPersec,PacketsOutboundDiscarded,PacketsOutboundErrors,PacketsReceivedDiscarded,PacketsReceivedErrors /value`

and

`wmic nic get MACAddress,name,NetEnabled,Speed,NetConnectionStatus,AdapterTypeId /value
`

Thanks.

**Comment by nathanwcy** [comment] 2019-11-06 10:54
`wmic path Win32_PerfRawData_Tcpip_NetworkInterface Get name,BytesReceivedPersec,BytesSentPersec,BytesTotalPersec,PacketsOutboundDiscarded,PacketsOutboundErrors,PacketsReceivedDiscarded,PacketsReceivedErrors /value`

BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=Realtek PCIe GBE Family Controller
PacketsOutboundDiscarded=0
PacketsOutboundErrors=0
PacketsReceivedDiscarded=0
PacketsReceivedErrors=0


BytesReceivedPersec=12523547
BytesSentPersec=720791
BytesTotalPersec=13244338
Name=Realtek PCIe GBE Family Controller _2
PacketsOutboundDiscarded=0
PacketsOutboundErrors=0
PacketsReceivedDiscarded=0
PacketsReceivedErrors=0


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=isatap.{2F04C954-07E2-43A4-9511-7A20E8C09528}
PacketsOutboundDiscarded=0
PacketsOutboundErrors=0
PacketsReceivedDiscarded=0
PacketsReceivedErrors=0


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=Teredo Tunneling Pseudo-Interface
PacketsOutboundDiscarded=0
PacketsOutboundErrors=0
PacketsReceivedDiscarded=0
PacketsReceivedErrors=0


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=isatap.{6742CDAE-8106-4B71-94A7-39F1FE598114}
PacketsOutboundDiscarded=0
PacketsOutboundErrors=0
PacketsReceivedDiscarded=0
PacketsReceivedErrors=0


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=isatap.lan
PacketsOutboundDiscarded=0
PacketsOutboundErrors=0
PacketsReceivedDiscarded=0
PacketsReceivedErrors=0


`wmic nic get MACAddress,name,NetEnabled,Speed,NetConnectionStatus,AdapterTypeId /value`

AdapterTypeId=
MACAddress=
Name=WAN Miniport (SSTP)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=WAN Miniport (IKEv2)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=WAN Miniport (L2TP)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=WAN Miniport (PPTP)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=WAN Miniport (PPPOE)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=WAN Miniport (IPv6)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=WAN Miniport (Network Monitor)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=0
MACAddress=30:85:A9:97:0E:D6
Name=Realtek PCIe GBE Family Controller
NetConnectionStatus=7
NetEnabled=FALSE
Speed=1000000000


AdapterTypeId=
MACAddress=
Name=WAN Miniport (IP)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=15
MACAddress=
Name=Microsoft ISATAP Adapter
NetConnectionStatus=
NetEnabled=
Speed=100000


AdapterTypeId=
MACAddress=
Name=RAS Async Adapter
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=15
MACAddress=
Name=Teredo Tunneling Pseudo-Interface
NetConnectionStatus=
NetEnabled=
Speed=100000


AdapterTypeId=0
MACAddress=08:57:00:EE:1F:60
Name=Realtek PCIe GBE Family Controller #2
NetConnectionStatus=2
NetEnabled=TRUE
Speed=100000000


AdapterTypeId=15
MACAddress=
Name=Microsoft ISATAP Adapter #2
NetConnectionStatus=
NetEnabled=
Speed=100000


AdapterTypeId=0
MACAddress=08:57:00:EE:1F:60
Name=Deterministic Network Enhancer Miniport
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=0
MACAddress=30:85:A9:97:0E:D6
Name=Deterministic Network Enhancer Miniport
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=0
MACAddress=8C:C6:20:52:41:53
Name=Deterministic Network Enhancer Miniport
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=0
MACAddress=8C:C6:20:52:41:53
Name=Deterministic Network Enhancer Miniport
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=Cisco Systems VPN Adapter for 64-bit Windows
NetConnectionStatus=4
NetEnabled=FALSE
Speed=


AdapterTypeId=
MACAddress=
Name=Deterministic Network Enhancer Miniport
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=15
MACAddress=
Name=Microsoft ISATAP Adapter #3
NetConnectionStatus=
NetEnabled=
Speed=100000


AdapterTypeId=
MACAddress=
Name=Bluetooth 设备(个人区域网)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=Bluetooth 设备(个人区域网)
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=15
MACAddress=
Name=Microsoft ISATAP Adapter
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=Apple Mobile Device Ethernet
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=
MACAddress=
Name=Deterministic Network Enhancer Miniport
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=0
MACAddress=00:FF:2F:04:C9:54
Name=TAP-Windows Adapter V9
NetConnectionStatus=7
NetEnabled=FALSE
Speed=100000000


AdapterTypeId=0
MACAddress=00:FF:2F:04:C9:54
Name=Deterministic Network Enhancer Miniport
NetConnectionStatus=
NetEnabled=
Speed=


AdapterTypeId=15
MACAddress=
Name=Microsoft ISATAP Adapter
NetConnectionStatus=
NetEnabled=
Speed=

**Comment by nathanwcy** [comment] 2019-11-06 11:05
The output of  `os.networkInterfaces()`

[[StableObjectId]]:5
iface:"本地连接 2"
ms:0
operstate:"unknown"
rx_bytes:0
rx_dropped:0
rx_errors:0
rx_sec:-1
tx_bytes:0
tx_dropped:0
tx_errors:0
tx_sec:-1

det.ifacename: "Realtek PCIe GBE Family Controller #2"
detail.name: "realtekpciegbefamilycontroller_2"
The **det.ifacename** not match with **detail.name**, this is why I replaced "#" characters to "_".

**Comment by sebhildebrandt** [comment] 2019-11-06 11:36
@nathanwcy Will investigate it the next few days. Need my working environment to check ;-) Thank you for your tests.

**Comment by sebhildebrandt** [comment] 2020-06-06 14:05
@NWIron sorry for the late reply! I now published a fix for this issue. Version 4.26.9 just released. Can you test it on your side?

**Closed by sebhildebrandt** 2020-06-06 14:05 UTC
Labels: Investigation
