### ISSUE TITLE
win32 - Module not found: Can't resolve 'osx-temperature-sensor'

### ISSUE THREAD

**Issue by maifeeulasad** [sebhildebrandt/systeminformation#291] opened 2019-11-02 07:00 UTC
**Describe the bug**
I'm using `systemiformation` in my windows pc, but it gives me **Module not found: Can't resolve 'osx-temperature-sensor'**, So I tried to install that, but yarn installing fails as this is a windows pc.

**To Reproduce**
1. used function 
```
const si = require('systeminformation');
si.cpu(function(data) {
    console.log('CPU Information:');
    console.log('- manufucturer: ' + data.manufacturer);
    console.log('- brand: ' + data.brand);
    console.log('- speed: ' + data.speed);
    console.log('- cores: ' + data.cores);
    console.log('- physical cores: ' + data.physicalCores);
    console.log('...');
})
```
2. See output/error 

[Here is a snap](https://drive.google.com/file/d/1YaRl2axXJHc--st-jITX-vMrOD1Fiut1/view?usp=sharing)

**Current Output**
*error*

**Expected behavior**
*print data about cpu*

**Environment (please complete the following information):**
 - systeminformation package version: ^4.14.17
 - OS: win10
 - Hardware : ASUS-X540

**Additional context**
--

**Comment by sebhildebrandt** [comment] 2019-11-02 08:16
@maifeeulasad  I guess you need to give me a little bit more information on your setup. I cannot reproduce this behavior within Nodejs. So in your screenshot I see that this is a react app. Are you trying to use systeminformation in a webbrowser/client? This will not work at all, because systeminformation is not intended to be used server side ... but maybe I got your setup wrong.

**Comment by maifeeulasad** [comment] 2019-11-02 14:00
Here , please take a look at [sandbox](https://codesandbox.io/s/frosty-snow-zpirj?fontsize=14), and I will add a video, I was running it on client machine and that gave me error, not on server side.

**Comment by sebhildebrandt** [comment] 2019-11-02 15:17
@maifeeulasad ok, this will definitely not work. systeminformation will only work on server side. Within a browser - due to security reasins - you cannot get that detailed system information (see also README - section Core Concept) . Closing it for now

**Closed by sebhildebrandt** 2019-11-02 15:17 UTC
