### ISSUE TITLE
Bug: memoryLayout is not working on Apple Silicon on Node 10

### ISSUE THREAD

**Issue by SanArGuz** [sebhildebrandt/systeminformation#755] opened 2022-12-22 18:27 UTC
**Describe the bug**
Hey, I noticed that memLayout on Darwin systems with Apple Silicon M1, running on node 10, is not getting information. 

**To Reproduce**
1. Run test/test.js
2. Select option M (memLayout)

**Current Output**
```
┌────────────────────────────────────────────────┐
│  Memory Layout                       v: 5.16.8 │
└────────────────────────────────────────────────┘
[]
Time to complete: 634.690ms
```
**Expected behavior**
when I run the command `system_profiler SPMemoryDataType` directly on the terminal it gets:
```
% system_profiler SPMemoryDataType
Memory:

      Memory: 32 GB
      Type: LPDDR5

```

**Environment:**
 - systeminformation package version:   "version": "5.16.8",
 - OS: macOs Monterrey 12.6.1
 - Hardware: MacBook pro 2021

**Comment by SanArGuz** [comment] 2022-12-22 18:32
Other test I made was:
```
const util = require('util');
const exec = util.promisify(require('child_process').exec);

async function lsExample() {
  const { stdout, stderr } = await exec('system_profiler SPMemoryDataType');
  console.log('stdout:', stdout);
  console.log('stderr:', stderr);
}
lsExample();
```
The output: 
```
% node index.js
stdout: Memory:

      Upgradeable Memory: Yes

        Memory Slot:

          Size: Empty
          Type: Empty
          Speed: Empty
          Status: Empty
          Manufacturer: Empty
          Part Number: Empty
          Serial Number: Empty


stderr:
``
```

**Comment by SanArGuz** [comment] 2022-12-22 18:35
When I ran the same script in node 14:

```
node index.js
stdout: Memory:

      Memory: 32 GB
      Type: LPDDR5


stderr: 
```

**Comment by sebhildebrandt** [comment] 2022-12-22 22:24
@SanArGuz ... I cannot reproduce this behavior ... I get 

```
┌────────────────────────────────────────────────┐
│  Memory Layout                       v: 5.16.8 │
└────────────────────────────────────────────────┘
[ { size: 34359738368,
    bank: '0',
    type: 'LPDDR5',
    ecc: false,
    clockSpeed: 0,
    formFactor: '',
    manufacturer: 'Apple',
    partNum: '',
    serialNum: '',
    voltageConfigured: null,
    voltageMin: null,
    voltageMax: null } ]
```

on my MacBook Pro M1 2021 with node.js 10

What is interesting is that you get different output of your own test above in nodejs 10 and nodejs 14 ... this is super strange and the output of your own test should be exactly the same ... just to be sure ... you are running it on the same machine and not running in a VM?? 

I get the same output of your test in node10 and node 18:

```
# node -v
v10.24.1
# node memTest.js
stdout: Memory:

      Memory: 32 GB
      Type: LPDDR5
      Manufacturer: Hynix


stderr:
```

**Comment by SanArGuz** [comment] 2022-12-23 15:24
@sebhildebrandt All the test were made in the actual machine and not in a VM.

I also made more test in 3 other machines, and the results were different in some cases:
### 1. Device 1 - Macbook 2021 M1 - OS monterrey
  - Node 10: 
```
Memory:

      Upgradeable Memory: Yes

        Memory Slot:

          Size: Empty
          ...
```
  - Node 14
```
stdout: Memory:

      Memory: 32 GB
      Type: LPDDR5
```

### 2. Device 2- Macbook 2021 M1 - OS monterrey
  - Node 10 and Node 14:
```
Memory:

      Upgradeable Memory: Yes

        Memory Slot:

          Size: Empty
          ...
```
### 3. Device 3- Macbook 2021 M1 - OS Ventura
  - Node 10 and Node 14
 ```
stdout: Memory:

      Memory: 32 GB
      Type: LPDDR5
```

Additionally I tested the command system_profiler SPMemoryDataType directly in all the terminals, and the result is:
```
% system_profiler SPMemoryDataType
Memory:

      Memory: 32 GB
      Type: LPDDR5
```

But in the device 2, it doesn't get anything.

This is very strange.

**Comment by sebhildebrandt** [comment] 2022-12-30 12:19
@SanArGuz ... as said, your test code should ALWAYS return back what you got back from `system_profiler SPMemoryDataType` independent on your node version. As the raw output from command line is the same on all machines, you should check WHY you are getting different results. I am afraid, I cannot reproduce it.

I will make some more tests on different Apple machines with node10 and node14 but I pretty much sure, that I cannot reproduce this.

**Comment by sebhildebrandt** [comment] 2023-01-05 13:13
@SanArGuz ... any updates from your side ... as I cannot reproduce your problem here on any machine, your help here would be fine.

**Comment by sebhildebrandt** [comment] 2023-01-25 17:28
@SanArGuz closing this for now as I cannot reproduce this and the output does not really make sense (at least this is not related to this package=. Feel free to reopen it, if you see anything new here.

**Closed by sebhildebrandt** 2023-01-25 17:28 UTC
Labels: Investigation
