### ISSUE TITLE
When call si.versions() opens alert to install command line tools

### ISSUE THREAD

**Issue by debelop13** [sebhildebrandt/systeminformation#132] opened 2018-06-01 11:46 UTC
Hello!

When called si.versions() opens alert to install command line tools.

Is because is calling a 'git' command, and some computers does not have installed this.

Thanks

**Comment by sebhildebrandt** [comment] 2018-06-01 11:49
Hi @debelop13  Can you provide your OS (including version), hardware and provide the exact call and the output? Thank you in advance

**Comment by debelop13** [comment] 2018-06-06 10:57
Hi

I am using macOS High Sierra 10.13.4

My exact call is this:         

async get() {
            var system =  await si.system();
            var cpu =  await si.cpu();
            var osInfo =  await si.osInfo();
            var versions =  await si.versions();
....
}

And if I comment this line 'var versions =  await si.versions();' git alert don't appear anymore
You have to uninstall git and xcode command line tools to reproduce it.

![screen shot 2018-06-06 at 12 56 10](https://user-images.githubusercontent.com/20789085/41034146-063530e4-6989-11e8-91e8-19bfb97db9e8.png)

**Comment by sebhildebrandt** [comment] 2018-06-06 10:59
OK, thank you!! need to find out, how I can avoid this ...

**Comment by Jelmerro** [comment] 2018-07-01 10:29
I recently tried one of my programs on the macbook of a friend, and came across the same issue. It seems that calling the git command will open this dialog even though git isn't installed yet. Maybe it could be solved by using `which git` instead of `git --version` to look for the installation directory. This way it should not execute the git command, and might prevent the dialog from opening. If it indicates git is installed somewhere, only then should the command `git --version` be called.

(relevant code here https://github.com/sebhildebrandt/systeminformation/blob/master/lib/osinfo.js#L340)

**Comment by sebhildebrandt** [comment] 2018-07-01 10:33
@Jelmerro - yes, this could be an idea. The problem is, that there IS a git installed in every case. If this is not the "original" git, then it is a `git` that then is responsible vor the popup. I still need to figure out, how I can avoid this.

**Comment by Jelmerro** [comment] 2018-07-01 10:38
I would expect the location to be different for this other git responsible for the popup, but I have no way to test or play with this currently.

**Comment by sebhildebrandt** [comment] 2018-07-01 11:22
You get the same result whether Xcode is installed or not:

```
$ which git
/usr/bin/git
```

:-( ... need to go deeper into this ...

**Comment by sebhildebrandt** [comment] 2018-07-03 21:08
I guess I have a fix for that. Would be great if you can test it ... just published version 3.42.1 ...

**Comment by sebhildebrandt** [comment] 2018-07-19 20:57
Closing it for now ... seems to be solved.

**Closed by sebhildebrandt** 2018-07-19 20:57 UTC
Labels: Investigation

**Comment by wenxin3262** [comment] 2018-08-15 17:58
@sebhildebrandt Still getting this prompt with the newest version

**Comment by sebhildebrandt** [comment] 2018-08-16 08:58
@wenxin3262  Which macOS version are you using? 
My routine to prevent this prompt depends a little on macOS versions ...

**Comment by FranCarrascosaMS** [comment] 2020-12-18 17:25
@sebhildebrandt, first of all, thanks for this repository, it's very useful!

In version 4.27.0, I'm getting a similar popup in macOS Catalina (10.15.5) but asking for `python3` command:

![image](https://user-images.githubusercontent.com/32394038/102642033-5a703880-415d-11eb-814a-0301970f3d3f.png)

I think users should not see this message and library must check if the command is installed before executing it, as @Jelmerro suggested.

**Comment by sebhildebrandt** [comment] 2020-12-18 17:53
@FranCarrascosaMS will start investigation.

**Comment by sebhildebrandt** [comment] 2020-12-19 19:42
@FranCarrascosaMS I pushed a version to GitHub that should solve the problem. Can you test it (you probably only need to download the lib/osinfo.js file ... thank you for a feedback. If this runs well, I will publish a new npm package version.

**Comment by FranCarrascosaMS** [comment] 2020-12-22 14:33
@sebhildebrandt, `python3` command requirement is gone but `pip3` arises now.

![image](https://user-images.githubusercontent.com/32394038/102899170-d1ae1100-446a-11eb-916b-f50b07a8c40a.jpeg)

Thanks!

**Comment by sebhildebrandt** [comment] 2020-12-22 14:41
@FranCarrascosaMS ... just pushed a new version V4.33.1 that should also cover this issue. Can you give it a try?

**Comment by FranCarrascosaMS** [comment] 2020-12-23 14:42
@sebhildebrandt, no popup is displayed! :DDD Thank you so much! 👏🏽👏🏽👏🏽
