### ISSUE TITLE
CPU Speed always prints max value

### ISSUE THREAD

**Issue by Turutupa** [sebhildebrandt/systeminformation#359] opened 2020-04-19 08:16 UTC
**Describe the bug**
Wether I use the cpu or cpuCurrentspeed I always the max value of my CPU not the current one.

I am running Windows 10.

**To Reproduce**
1. used function 'si.cpu' and 'si.cpuCurrentspeed' and I always get the same value, in min, max and average.
2. code snippet `const si = require("systeminformation");

// promises style - new since version 3
const cpu = () =>
  si
    .cpu()
    .then((data) => {
      console.log("CPU Information:");
      console.log("- speed: " + data.speed);
      console.log("...");
    })
    .catch((error) => console.error(error));

const cpuCurrentSpeed = () =>
  si.cpuCurrentspeed().then((data) => {
    console.log("CPU SPEED INformation");
    console.log(data);
  });

const cpuLogging = setInterval(() => {
  cpu();
  cpuCurrentSpeed();
}, 500);`
3. start app / code
4. See output/error No output error, just wrong values?

**Current Output**
I always get the value 3,79

**Expected behavior**
In my task manager I can see the cpu get values between 1.4GHZ and 2.5GHz because not doing any heavy tasks but output value is always 3,79.

**Environment (please complete the following information):**
 - systeminformation package version: "^4.23.3"
 - OS: Windows 10 Pro

**Additional context**

I tried looking for answers in google and the Issues section but didn't find anything. Thanks in advance. Still the tool is awesome!

**Comment by sebhildebrandt** [comment] 2020-04-19 09:04
@Turutupa this is due to the nodes implementation in Windows. For other OS nodejs provides proper information per core when  you try:

```
# node
> os.cpus()
```

But in Windows this returns the same speed information for all cores

Example Output for Linux:

```
os.cpus()
[
  {
    model: 'Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz',
    speed: 1749,
    times: {
      user: 110235000,
      nice: 39400,
      sys: 40113600,
      idle: 61103846400,
      irq: 0
    }
  },
  {
    model: 'Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz',
    speed: 1764,
    times: {
      user: 122637300,
      nice: 61600,
      sys: 41900400,
      idle: 61106876300,
      irq: 0
    }
  },
  {
    model: 'Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz',
    speed: 850,
    times: {
      user: 128430000,
      nice: 18000,
      sys: 44531400,
      idle: 61100397700,
      irq: 0
    }
  },
  {
    model: 'Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz',
    speed: 800,
    times: {
      user: 128632300,
      nice: 35000,
      sys: 44129700,
      idle: 61100339100,
      irq: 0
    }
  },
 ...
```

As you can see the `speed` is different per core. I am currently trying to implement another way for Windows (version 10) that might be better than the current nodejs based approach. Will inform you as soon as I have a first version of that.

**Comment by Turutupa** [comment] 2020-04-19 09:44
Hey, thanks for the quick response, good to know! This would be an awesome feature to have. 

Keep up the good work, the tool is amazing! 👏👏🙌😃

**Comment by sebhildebrandt** [comment] 2020-04-19 10:40
@Turutupa I made some more research and this is quite complicated because the performance counter keys in windows are translated (does not make sense to me!). So basically getting the right counters would first need to be translated. As I also found a way to get the correct values this would be doable but this is a time consuming (getting translations strings takes several seconds).... :-( ... I do not know if I can implement a good solution here

**Comment by Turutupa** [comment] 2020-04-19 11:01
@sebhildebrandt I have been researching and perhaps this is doable with python. I'd rather do it with node cause I am developing an Electron.js app but as long as it works I'm fine with it. This would be the code snipper 

`import wmi

computer = wmi.WMI()
computer_info = computer.Win32_ComputerSystem()[0]
os_info = computer.Win32_OperatingSystem()[0]
proc_info = computer.Win32_Processor()[0]
gpu_info = computer.Win32_VideoController()[0]

os_name = os_info.Name.encode('utf-8').split(b'|')[0]
os_version = ' '.join([os_info.Version, os_info.BuildNumber])
system_ram = float(os_info.TotalVisibleMemorySize) / 1048576  # KB to GB

print('OS Name: {0}'.format(os_name))
print('OS Version: {0}'.format(os_version))
print('CPU: {0}'.format(proc_info.Name))
print('RAM: {0} GB'.format(system_ram))
print('Graphics Card: {0}'.format(gpu_info.Name))`

And this the output

`OS Name: Microsoft Windows 7 Ultimate 
OS Version: 6.1.7601 7601
CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
RAM: 15.9443855286 GB
Graphics Card: NVIDIA GeForce GTX 960`

This approach only works for windows but I think this is ok at the moment.

_source: https://stackoverflow.com/questions/38103690/get-system-informationcpu-speed-total-ram-graphic-card-model-etc-under-window_

**Comment by Turutupa** [comment] 2020-04-19 11:22
Yeah.. I don't know how to get this value... Even trying to get it from cmd is hard... it always shows my max clockspeed :(

**Comment by sebhildebrandt** [comment] 2020-04-19 11:40
@Turutupa to your above code: This does not give the current cpu frequency. There IS one method (using PowerShell) to get it but the problem is, that I need to translate the counter key values (Microsoft made it hard to get this language independent ... don't know why) ...

**Comment by Turutupa** [comment] 2020-04-19 11:42
Just out of curiosity, how do you get it via powershell? Because I was trying to figure it out and still was only able to get Max Clock Speed :(

**Comment by sebhildebrandt** [comment] 2020-04-19 11:47
Can you try this in PowerShell and provide the results here:

```
Get-Counter -Counter "\Processor Information(*)\Processor Frequency"
```

I will then implement is this way as a first step with untranslated key strings (which then will only work in English windows versions)

**Comment by Turutupa** [comment] 2020-04-19 11:50
Sorry it is unformatted but you can get the idea. The values are always the same.

``` 
Timestamp                 CounterSamples
---------                 --------------
4/19/2020 1:48:14 PM      \\desktop-ofpuvj1\processor information(_total)\processor frequency :
                          3792

                          \\desktop-ofpuvj1\processor information(0,_total)\processor frequency :
                          3792

                          \\desktop-name\processor information(0,3)\processor frequency :
                          3792

                          \\desktop-name\processor information(0,2)\processor frequency :
                          3792

                          \\desktop-name\processor information(0,1)\processor frequency :
                          3792

                          \\desktop-name\processor information(0,0)\processor frequency :
                          3792
```

**Comment by sebhildebrandt** [comment] 2020-04-19 11:51
@Turutupa Thank you!
OK so also not a way to go ... :-(

**Comment by Turutupa** [comment] 2020-04-19 13:54
@sebhildebrandt Unfortunately not 😅😅😅

**Comment by sebhildebrandt** [comment] 2020-04-19 16:19
closing this for now, as I do not really see a way to solve this.

**Closed by sebhildebrandt** 2020-04-19 16:19 UTC
Labels: enhancement
