### ISSUE TITLE
getStaticData not working

### ISSUE THREAD

**Issue by rkdhatterwal** [sebhildebrandt/systeminformation#189] opened 2018-12-27 16:43 UTC
### Issue Type
* [x] Bug

### Expected behavior 

- 
- 
- 

### Actual behavior

- 
- 
- 

### Steps to reproduce the problem

-
-
-

### Specifications 
-nodejs version: 6.4.1
-electron version: 4.0.0
- package version: 3.52.2
- operating system: Mac OSX Mojave
- hardware:

### Problem and possible solution

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ...

**Comment by sebhildebrandt** [comment] 2018-12-27 20:15
@rkdhatterwal I guess it should be 

- npm v. 6.4.1
- node v. 10.x
- electron 4.0.0

Well, as I cannot reproduce this error, can you provide the code you are trying to run? What hardware are you using? If you try this (not using electron), do you get any results? Can you provide the output of 

```
const si = require('systeminformation');

si.getStaticData().then(result => {
    console.log(result)
})
```

Thank you in advance!

**Comment by sebhildebrandt** [comment] 2018-12-27 20:35
@rkdhatterwal one more thing: could you please update the library to v3.52.3?

**Comment by rkdhatterwal** [comment] 2018-12-28 17:19
node and npm version are the one you mentions @sebhildebrandt 
Hardware detail: MacBook Pro 15 running MacOSX Mojave
I have updated the library to v3.52.4 and npm and node also. I have executed the code without electron. Still no result.
If i downgrade the library to v3.41.3 it works perfectly fine.

The result i got in v3.41.3 is as below:

{ version: '3.41.3',
  system:
   { manufacturer: 'Apple Inc.',
     model: 'MacBookPro11,2',
     version: '1.0',
     serial: '',
     uuid: '',
     sku: '' },
  bios:
   { vendor: 'Apple Inc.',
     version: '',
     releaseDate: '',
     revision: '' },
  baseboard:
   { manufacturer: 'Apple Inc.',
     model: 'MacBookPro11,2',
     version: '1.0',
     serial: '',
     assetTag: '' },
  os:
   { platform: 'darwin',
     distro: 'Mac OS X',
     release: '10.14.2',
     codename: '',
     kernel: '18.2.0',
     arch: 'x64',
     hostname: 'ezero',
     logofile: 'apple' },
  versions:
   { kernel: '18.2.0',
     openssl: '1.1.0j',
     node: '11.6.0',
     v8: '7.0.276.38-node.13',
     npm: '6.5.0-next.0',
     yarn: '',
     pm2: '',
     gulp: '',
     grunt: '',
     git: '2.17.2',
     tsc: '',
     mysql: '',
     redis: '',
     mongodb: '',
     nginx: '',
     php: '7.1.20' },
  cpu:
   { manufacturer: 'Intel®',
     brand: 'Core™ i7-4750HQ',
     vendor: 'GenuineIntel',
     family: '6',
     model: '70',
     stepping: '1',
     revision: '',
     voltage: '',
     speed: '2.00',
     speedmin: '2.00',
     speedmax: '2.00',
     cores: 8,
     cache: { l1d: 32768, l1i: 32768, l2: 262144, l3: 6291456 },
     flags:
      'fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clfsh ds acpi mmx fxsr sse sse2 ss htt tm pbe sse3 pclmulqdq dtes64 mon dscpl vmx est tm2 ssse3 fma cx16 tpr pdcm sse4.1 sse4.2 x2apic movbe popcnt aes pcid xsave osxsave seglim64 tsctmr avx1.0 rdrand f16c' },
  graphics: { controllers: [ [Object] ], displays: [ [Object] ] },
  net:
   [ { iface: 'lo0',
       ip4: '127.0.0.1',
       ip6: '::1',
       mac: '',
       internal: true },
     { iface: 'en0',
       ip4: '192.168.1.104',
       ip6: 'fe80::1018:f64f:5121:2438',
       mac: '78:31:c1:cd:d9:4e',
       internal: false },
     { iface: 'awdl0',
       ip4: '',
       ip6: 'fe80::434:a4ff:fe9b:27ff',
       mac: '06:34:a4:9b:27:ff',
       internal: false },
     { iface: 'utun0',
       ip4: '',
       ip6: 'fe80::4a9b:4bb2:e207:eaaa',
       mac: '',
       internal: false } ],
  memLayout:
   [ { size: 4294967296,
       bank: 'BANK 0/DIMM0:',
       type: 'DDR3',
       clockSpeed: 1600,
       formFactor: '',
       manufacturer: 'Micron Technology Inc.',
       partNum: '0x384B54463531323634485A2D314736453120',
       serialNum: '-',
       voltageConfigured: -1,
       voltageMin: -1,
       voltageMax: -1 },
     { size: 4294967296,
       bank: 'BANK 1/DIMM0:',
       type: 'DDR3',
       clockSpeed: 1600,
       formFactor: '',
       manufacturer: 'Micron Technology Inc.',
       partNum: '0x384B54463531323634485A2D314736453120',
       serialNum: '-',
       voltageConfigured: -1,
       voltageMin: -1,
       voltageMax: -1 } ],
  diskLayout:
   [ { type: 'SSD',
       name: 'APPLE SSD SM0256F',
       vendor: '',
       size: 251000193024,
       bytesPerSector: -1,
       totalCylinders: -1,
       totalHeads: -1,
       totalSectors: -1,
       totalTracks: -1,
       tracksPerCylinder: -1,
       sectorsPerTrack: -1,
       firmwareRevision: 'UXM2JA1Q',
       serialNum: 'S1K4NYBF164657',
       interfaceType: 'PCI' } ] }

**Comment by sebhildebrandt** [comment] 2018-12-28 17:38
Thank you @rkdhatterwal 

Seems that one of the following underlying functions causes the error:

May I ask to try them seperately:

```
const si = require('systeminformation');
si.system().then(data => console.log(data))
```

Same for the others:

```
si.bios().then(data => console.log(data))
si.baseboard().then(data => console.log(data))
si.osInfo().then(data => console.log(data))
si.uuid().then(data => console.log(data))
si.versions().then(data => console.log(data))
si.cpu().then(data => console.log(data))
si.cpuFlags().then(data => console.log(data))
si.graphics().then(data => console.log(data))
si.networkInterfaces().then(data => console.log(data))
si.memLayout().then(data => console.log(data))
si.diskLayout().then(data => console.log(data))
```

I guess that one of those causes the problem here ...

**Comment by rkdhatterwal** [comment] 2018-12-28 17:48
si.versions().then(data => console.log(data));
Versions function didn't return anything. Remaining functions returned correct data.

**Comment by sebhildebrandt** [comment] 2018-12-28 22:12
OK, I guess I found the problem ... just published a new version 3.52.6. Can you test it on your side?

May I ask one more question: as you got version information for `git` and it seems that you did not installed Xcode developer tools, did you installed `git` via homebrew  (with `brew install git`)? If yes, would you once again post your output of 

```
si.versions().then(data => console.log(data));
```

with the latest published version of systeminformation? I tried to also handle this case correctly.

**Comment by sebhildebrandt** [comment] 2018-12-29 08:17
A litte progress! So this means, that my approach to detect if command line tools are installed is not that reliable ;-)

Can you have a look, if one of the following path exists?

```
/Library/Developer/
/Library/Developer/CommandLineTools/
/Applications/Xcode.app/Contents/Developer/Tools
```

Thank you once again!

**Comment by sebhildebrandt** [comment] 2018-12-29 10:20
Ok, I expected that somehow. In the `/Library/Developer` path, what ist the content ? Thank you once again for your support here.

**Comment by sebhildebrandt** [comment] 2018-12-29 12:30
Version 3.52.7 published. Detection of installed command line tools improved. So hopefully now it will also show git version on your machine. Would you be so kind to test it? Thank you in advance.

**Comment by rkdhatterwal** [comment] 2018-12-30 13:06
@sebhildebrandt  Updated the library to v3.54.0. The output of `si.versions()` is as below:
`Versions:
{ kernel: '18.2.0',
  openssl: '1.1.0j',
  systemOpenssl: '2.6.5',
  systemOpensslLib: 'LibreSSL',
  node: '11.6.0',
  v8: '7.0.276.38-node.13',
  npm: '6.5.0-next.0',
  yarn: '',
  pm2: '',
  gulp: '',
  grunt: '',
  git: '2.17.2',
  tsc: '',
  mysql: '',
  redis: '',
  mongodb: '',
  nginx: '',
  php: '7.1.20',
  docker: '',
  postfix: '3.2.2',
  postgresql: '',
  perl: '5.18.2',
  python: '2.7.10',
  gcc: '4.2.1' }'

**Comment by sebhildebrandt** [comment] 2018-12-30 13:08
Perfect. I think we can close this issue now.

**Closed by sebhildebrandt** 2018-12-30 13:08 UTC
Labels: bug
