### ISSUE TITLE
Wifi Bssid is returned in a shortened format

### ISSUE THREAD

**Issue by gilisegal** [sebhildebrandt/systeminformation#524] opened 2021-04-19 09:28 UTC
The wifiConnections() function returns the wifi bssid in a shortened format.
For example, a full bssid returned in wifiNetworks() : 00:b8:c2:39:55:0a
Is returned in the wifiConnections() as: 0:b8:c2:39:55:a.

**Comment by sebhildebrandt** [comment] 2021-04-19 09:29
@gilisegal ohh ... will have a look on it ... Platform? (linux/win/macOS)??

**Comment by gilisegal** [comment] 2021-04-19 09:30
macOS.

Thanks!

**Comment by sebhildebrandt** [comment] 2021-04-19 09:35
@sebhildebrandt Hmmmm ... cannot reproduce this. And I cannot spot the part in the code where I would trim it somehow.

Can you run the following command on your machine and post the result as a text:

```
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I
```

Best regards

**Comment by gilisegal** [comment] 2021-04-19 09:38
This is the result:

     agrCtlRSSI: -58
     agrExtRSSI: 0
    agrCtlNoise: -95
    agrExtNoise: 0
          state: running
        op mode: station 
     lastTxRate: 585
        maxRate: 1300
lastAssocStatus: 0
    802.11 auth: open
      link auth: wpa2-psk
          BSSID: 0:b8:c2:39:55:a
           SSID: Chen_Gili
            MCS: 7
        channel: 40,80

**Comment by sebhildebrandt** [comment] 2021-04-19 09:40
@gilisegal OK, so macOS returns incorrect values. What is your hardware?

**Comment by gilisegal** [comment] 2021-04-19 09:49
I've checked in 2 macs, both are macOS Catalina 10.15.7
One is MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
The other is MacBook Pro (15-inc, 2018)

**Comment by sebhildebrandt** [comment] 2021-04-19 14:39
@gilisegal if both return wrong values, I have the feeling (in the same network), that it could also has something to do with the combination wifi network / macOS airport call ... 

As macOS returns wrong values (and I cannot reproduce this -  all my machines already run on Big Sur ...), I might not be able to solve it. Closing it for now.

**Closed by sebhildebrandt** 2021-04-19 14:39 UTC
