### ISSUE TITLE
can not get two disks information both

### ISSUE THREAD

**Issue by andy259** [sebhildebrandt/systeminformation#101] opened 2018-01-10 13:46 UTC
### Issue Type

* [√ ] Bug

### Expected behavior 

-  get two disks infromation both

### Actual behavior

-  just get hard disk infromation another ssd disk not get

### Steps to reproduce the problem
this is my code
``` js
const si = require('systeminformation');
si.diskLayout(function(data){
    console.log(data);
});
//print: [{...}]
// and return data have a little wrong : type was SSD,but name was a hard disk name.
// besides I get the serialNum was hard disk not SSD. 
```

### Specifications 

- package version: 3.33.12
- operating system: windows 10 (ps.system was installed on ssd disk)
- hardware: one Samsung ssd disk another HGST hard disk

### Last
Looking forward to your recovery and sorry for my English.

**Comment by sebhildebrandt** [comment] 2018-01-10 14:52
Will have a look at it tonight

**Comment by sebhildebrandt** [comment] 2018-01-12 10:16
Can you provide the results of the output of the code you provided what your `console.log(data)` returned. I need to see what exacly is wrong. 

Please provede also the output of the following comman in your console (command line):

```
wmic diskdrive get /value
```

Thank you in advance!

**Comment by sebhildebrandt** [comment] 2018-01-17 08:41
Closing it for now. Cannot reproduce problem, and didn‘t get any further information from requester.

**Comment by andy259** [comment] 2018-01-17 13:13
Sorry for late.
I hvae updated to Version:3.33.13
there is <code>console.log(data) </code>:
<pre>
[ { type: 'SSD',  
    name: 'HGST HTS725050A7E630',  
    vendor: '(��׼����������)',    
    size: 500105249280,
    bytesPerSector: 512,    
    totalCylinders: 60801,
    totalHeads: 255,    
    totalSectors: 976768065,
    totalTracks: 15504255,
    tracksPerCylinder: 255,
    sectorsPerTrack: 63,
    firmwareRevision: 'GH2ZB550',
    serialNum: 'TF755AY9KX1MJM',
    interfaceType: 'IDE' } ]
</pre>
And there is <code>wmic diskdrive get /value</code>:
<pre>

Availability=
BytesPerSector=512
Capabilities={3,4}
CapabilityDescriptions={"Random Access","Supports Writing"}
Caption=HGST HTS725050A7E630
CompressionMethod=
ConfigManagerErrorCode=0
ConfigManagerUserConfig=FALSE
CreationClassName=Win32_DiskDrive
DefaultBlockSize=
Description=磁盘驱动器
DeviceID=\\.\PHYSICALDRIVE1
ErrorCleared=
ErrorDescription=
ErrorMethodology=
FirmwareRevision=GH2ZB550
Index=1
InstallDate=
InterfaceType=IDE
LastErrorCode=
Manufacturer=(标准磁盘驱动器)
MaxBlockSize=
MaxMediaSize=
MediaLoaded=TRUE
MediaType=Fixed hard disk media
MinBlockSize=
Model=HGST HTS725050A7E630
Name=\\.\PHYSICALDRIVE1
NeedsCleaning=
NumberOfMediaSupported=
Partitions=2
PNPDeviceID=SCSI\DISK&amp;VEN_HGST&amp;PROD_HTS725050A7E630\4&amp;248D3288&amp;0&amp;010000
PowerManagementCapabilities=
PowerManagementSupported=
SCSIBus=1
SCSILogicalUnit=0
SCSIPort=0
SCSITargetId=0
SectorsPerTrack=63
SerialNumber=      TF755AY9KX1MJM
Signature=3340720380
Size=500105249280
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=DESKTOP-GES4M4A
TotalCylinders=60801
TotalHeads=255
TotalSectors=976768065
TotalTracks=15504255
TracksPerCylinder=255


Availability=
BytesPerSector=512
Capabilities={3,4}
CapabilityDescriptions={"Random Access","Supports Writing"}
Caption=Samsung SSD 850 EVO 120GB
CompressionMethod=
ConfigManagerErrorCode=0
ConfigManagerUserConfig=FALSE
CreationClassName=Win32_DiskDrive
DefaultBlockSize=
Description=磁盘驱动器
DeviceID=\\.\PHYSICALDRIVE0
ErrorCleared=
ErrorDescription=
ErrorMethodology=
FirmwareRevision=EMT02B6Q
Index=0
InstallDate=
InterfaceType=IDE
LastErrorCode=
Manufacturer=(标准磁盘驱动器)
MaxBlockSize=
MaxMediaSize=
MediaLoaded=TRUE
MediaType=Fixed hard disk media
MinBlockSize=
Model=Samsung SSD 850 EVO 120GB
Name=\\.\PHYSICALDRIVE0
NeedsCleaning=
NumberOfMediaSupported=
Partitions=3
PNPDeviceID=SCSI\DISK&amp;VEN_SAMSUNG&amp;PROD_SSD_850_EVO_120G\4&amp;248D3288&amp;0&amp;000000
PowerManagementCapabilities=
PowerManagementSupported=
SCSIBus=0
SCSILogicalUnit=0
SCSIPort=0
SCSITargetId=0
SectorsPerTrack=63
SerialNumber=S21SNX2J502100F
Signature=220531512
Size=120031511040
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=DESKTOP-GES4M4A
TotalCylinders=14593
TotalHeads=255
TotalSectors=234436545
TotalTracks=3721215
TracksPerCylinder=255
</pre>

**Comment by sebhildebrandt** [comment] 2018-01-17 13:32
Will check it! Thank you for providing additional information!

**Comment by sebhildebrandt** [comment] 2018-01-17 22:06
Just published a new version 3.33.14 - not sure if this fixes the error. Can you test it on your machine?
Thank you

**Comment by andy259** [comment] 2018-01-18 10:50
Yes,I got the right data:
<pre>
[ { type: 'HD',
    name: 'HGST HTS725050A7E630',
    vendor: '(��׼����������)',
    size: 500105249280,
    bytesPerSector: 512,
    totalCylinders: 60801,
    totalHeads: 255,
    totalSectors: 976768065,
    totalTracks: 15504255,
    tracksPerCylinder: 255,
    sectorsPerTrack: 63,
    firmwareRevision: 'GH2ZB550',
    serialNum: 'TF755AY9KX1MJM',
    interfaceType: 'IDE' },
  { type: 'SSD',
    name: 'Samsung SSD 850 EVO 120GB',
    vendor: '(��׼����������)',
    size: 120031511040,
    bytesPerSector: 512,
    totalCylinders: 14593,
    totalHeads: 255,
    totalSectors: 234436545,
    totalTracks: 3721215,
    tracksPerCylinder: 255,
    sectorsPerTrack: 63,
    firmwareRevision: 'EMT02B6Q',
    serialNum: 'S21SNX2J502100F',
    interfaceType: 'IDE' } ]
</pre>
Thank you so much!

**Comment by sebhildebrandt** [comment] 2018-01-18 12:11
Great, @andy259 thank you for your support on that

**Closed by sebhildebrandt** 2018-01-18 12:11 UTC
Labels: bug
